/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Classes;

import java.awt.Cursor;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileFilter;
import java.io.FileReader;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Stream;
import javax.swing.JOptionPane;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author icaro.souza
 */
public class GeraPdfArquivo extends javax.swing.JFrame {

    /**
     * Creates new form GeraPdfArquivo
     */
    public GeraPdfArquivo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Gerencia = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNomePasta = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Gerencia.setText("GERENCIA DE PROTESTO DE TITULOS DE CREDITO-GEPROT");

        jLabel1.setText("Documento:");

        jTextFieldNomePasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomePastaActionPerformed(evt);
            }
        });

        jButton1.setText("buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Processar Arquivo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(327, 327, 327)
                .addComponent(jButton2)
                .addContainerGap(349, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(163, 163, 163)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Gerencia, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(jTextFieldNomePasta, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton1)))
                    .addContainerGap(164, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(230, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(47, 47, 47))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(108, 108, 108)
                    .addComponent(Gerencia, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jTextFieldNomePasta, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1))
                    .addContainerGap(109, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNomePastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomePastaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomePastaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        JFileChooser chooser = new JFileChooser();//filtro de arquivos
        FileNameExtensionFilter filter = new FileNameExtensionFilter("TEXT FILES", "txt", "text");
        chooser.setFileFilter(filter);
        chooser.setCurrentDirectory(new java.io.File("."));
        chooser.setDialogTitle("Selecionar Arquivo");//codigo de seleçao das pastas
        //chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.setAcceptAllFileFilterUsed(false);
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            jTextFieldNomePasta.setText(chooser.getSelectedFile().toString());

            System.out.println("getCurrentDirectory(): "

                +  chooser.getCurrentDirectory()+"\n");
            System.out.println("getSelectedFile() : "
                +  chooser.getSelectedFile()+"\n");//
        }
        else {
            System.out.println("No Selection "+"\n");
        }
        

    }//GEN-LAST:event_jButton1ActionPerformed
    
    public String formatarValor(String s){ //formata os valores para moeda real
        try{
        double d = Double.parseDouble(s)/ 100;
        NumberFormat formater = new DecimalFormat("##,###,###,##0.00");
        System.out.println(formater.format(d));
        return formater.format(d);
        
        }catch(NumberFormatException ex){
            return "";
        }
}
    
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        String saida ="";
        saida +="";
        Assunto a;
        a = new Assunto();
        List<Assunto> assuntos = new ArrayList<Assunto>();
        
       assuntos.add(a);
       if(jTextFieldNomePasta.getText().equals("")){
             JOptionPane.showMessageDialog(null,"Por favor Insere o arquivo!");
             return;
        }
        File arquivo = new File(jTextFieldNomePasta.getText()); 
        JOptionPane.showMessageDialog(null,"Aguarde");
        try{
            BufferedReader b = new BufferedReader(new FileReader(arquivo));
            String linha = "";
            String certAux = "";
            String certidao = "";
            String nome="";
            String cDataDef1,cDataDef2,cDataDef3,cDataDef4,cDataDef5,cDataDef6,cDataDef7,cDataDef8;
            cDataDef1 = cDataDef2 = cDataDef3 =cDataDef4 = cDataDef5 = cDataDef6 = cDataDef7 = cDataDef8 = "";
            
            String bData1,bData2,bData3,bData4,bData5,bData6,bData7,bData8;
            bData1=bData2=bData3=bData4=bData5=bData6=bData7=bData8="";
            
            String bNumero1,bNumero2,bNumero3,bNumero4,bNumero5,bNumero6,bNumero7,bNumero8;
            bNumero1=bNumero2=bNumero3=bNumero4=bNumero5=bNumero6=bNumero7=bNumero8="";
            
            String bOrdem1,bOrdem2,bOrdem3,bOrdem4,bOrdem5,bOrdem6,bOrdem7,bOrdem8;
            bOrdem1=bOrdem2=bOrdem3=bOrdem4=bOrdem5=bOrdem6=bOrdem7=bOrdem8="";
            
            String bNatureza1,bNatureza2,bNatureza3,bNatureza4,bNatureza5,bNatureza6,bNatureza7,bNatureza8;
            bNatureza1=bNatureza2=bNatureza3=bNatureza4=bNatureza5=bNatureza6=bNatureza7=bNatureza8="";
            
            String dPrincipal1,dPrincipal2,dPrincipal3,dPrincipal4,dPrincipal5,dPrincipal6,dPrincipal7,dPrincipal8;
            dPrincipal1=dPrincipal2=dPrincipal3=dPrincipal4=dPrincipal5=dPrincipal6=dPrincipal7=dPrincipal8="";
            
            String dMulta1,dMulta2,dMulta3,dMulta4,dMulta5,dMulta6,dMulta7,dMulta8;
            dMulta1=dMulta2=dMulta3=dMulta4=dMulta5=dMulta6=dMulta7=dMulta8="";
            
            String dCorrecao1,dCorrecao2,dCorrecao3,dCorrecao4,dCorrecao5,dCorrecao6,dCorrecao7,dCorrecao8;
            dCorrecao1=dCorrecao2=dCorrecao3=dCorrecao4=dCorrecao5=dCorrecao6=dCorrecao7=dCorrecao8="";
            
            String dJuros1,dJuros2,dJuros3,dJuros4,dJuros5,dJuros6,dJuros7,dJuros8;
            dJuros1=dJuros2=dJuros3=dJuros4=dJuros5=dJuros6=dJuros7=dJuros8="";
            
            String dTotal1,dTotal2,dTotal3,dTotal4,dTotal5,dTotal6,dTotal7,dTotal8;
            dTotal1=dTotal2=dTotal3=dTotal4=dTotal5=dTotal6=dTotal7=dTotal8="";
            
            String dTotalAtual1,dTotalAtual2,dTotalAtual3,dTotalAtual4,dTotalAtual5,dTotalAtual6,dTotalAtual7,dTotalAtual8;
            dTotalAtual1=dTotalAtual2=dTotalAtual3=dTotalAtual4=dTotalAtual5=dTotalAtual6=dTotalAtual7=dTotalAtual8="";
            
            String eDespesa1,eDespesa2,eDespesa3,eDespesa4,eDespesa5,eDespesa6,eDespesa7,eDespesa8;
            eDespesa1=eDespesa2=eDespesa3=eDespesa4=eDespesa5=eDespesa6=eDespesa7=eDespesa8="";
            
            String eHonorarios1,eHonorarios2,eHonorarios3,eHonorarios4,eHonorarios5,eHonorarios6,eHonorarios7,eHonorarios8;
            eHonorarios1=eHonorarios2=eHonorarios3=eHonorarios4=eHonorarios5=eHonorarios6=eHonorarios7=eHonorarios8="";
            
            String fCorrecao1,fCorrecao2,fCorrecao3,fCorrecao4,fCorrecao5,fCorrecao6,fCorrecao7,fCorrecao8;
            fCorrecao1=fCorrecao2=fCorrecao3=fCorrecao4=fCorrecao5=fCorrecao6=fCorrecao7=fCorrecao8="";
            
            String fJuros1,fJuros2,fJuros3,fJuros4,fJuros5,fJuros6,fJuros7,fJuros8;
            fJuros1=fJuros2=fJuros3=fJuros4=fJuros5=fJuros6=fJuros7=fJuros8="";
            
            String tTotalInicial,tTotalAtualizado;
            tTotalInicial=tTotalAtualizado="";
            
                    
            linha = b.readLine();
            while(linha.startsWith("0")) linha = b.readLine();
            while(linha != null){
                certidao = linha.substring(2, 12);
                if(!certidao.equals(certAux)){
                   // geraPdf();
                   //Compilação do JRXML
                    JasperReport report;
                    try {
                        report = JasperCompileManager.compileReport("//pgsrv08/publico/relatorios/producao/certidao_final.jrxml");
                        
                        Map<String,Object> parametros = new HashMap<String,Object>();  
                        
                        parametros.put("Anome", nome);
                        parametros.put("Bnumero1", bNumero1);
                        parametros.put("Bnumero2", bNumero2);
                        parametros.put("Bnumero3", bNumero3);
                        parametros.put("Bnumero4", bNumero4);
                        parametros.put("Bnumero5", bNumero5);
                        parametros.put("Bnumero6", bNumero6);
                        parametros.put("Bnumero7", bNumero7);
                        parametros.put("Bnumero8", bNumero8);
                        parametros.put("Bdata1", bData1);
                        parametros.put("Bdata2", bData2);
                        parametros.put("Bdata3", bData3);
                        parametros.put("Bdata4", bData4);
                        parametros.put("Bdata5", bData5);
                        parametros.put("Bdata6", bData6);
                        parametros.put("Bdata7", bData7);
                        parametros.put("Bdata8", bData8);
                        parametros.put("Bordem1", bOrdem1);
                        parametros.put("Bordem2", bOrdem2);
                        parametros.put("Bordem3", bOrdem3);
                        parametros.put("Bordem4", bOrdem4);
                        parametros.put("Bordem5", bOrdem5);
                        parametros.put("Bordem6", bOrdem6);
                        parametros.put("Bordem7", bOrdem7);
                        parametros.put("Bordem8", bOrdem8);
                        parametros.put("Bnatureza1", bNatureza1);
                        parametros.put("Bnatureza2", bNatureza2);
                        parametros.put("Bnatureza3", bNatureza3);
                        parametros.put("Bnatureza4", bNatureza4);
                        parametros.put("Bnatureza5", bNatureza5);
                        parametros.put("Bnatureza6", bNatureza6);
                        parametros.put("Bnatureza7", bNatureza7);
                        parametros.put("Bnatureza8", bNatureza8);
                        parametros.put("Bnumero8", bNumero8);
                        parametros.put("Cdatadefi1", cDataDef1);
                        parametros.put("Cdatadefi2", cDataDef2);
                        parametros.put("Cdatadefi3", cDataDef3);
                        parametros.put("Cdatadefi4", cDataDef4);
                        parametros.put("Cdatadefi5", cDataDef5);
                        parametros.put("Cdatadefi6", cDataDef6);
                        parametros.put("Cdatadefi7", cDataDef7);
                        parametros.put("Cdatadefi8", cDataDef8);
                        
                        parametros.put("Dprincipal1", formatarValor(dPrincipal1));
                        parametros.put("Dprincipal2", formatarValor(dPrincipal2));
                        parametros.put("Dprincipal3", formatarValor(dPrincipal3));
                        parametros.put("Dprincipal4", formatarValor(dPrincipal4));
                        parametros.put("Dprincipal5", formatarValor(dPrincipal5));
                        parametros.put("Dprincipal6", formatarValor(dPrincipal6));
                        parametros.put("Dprincipal7", formatarValor(dPrincipal7));
                        parametros.put("Dprincipal8", formatarValor(dPrincipal8));
                        
                        parametros.put("Dmulta1", formatarValor(dMulta1));
                        parametros.put("Dmulta2", formatarValor(dMulta2));
                        parametros.put("Dmulta3", formatarValor(dMulta3));
                        parametros.put("Dmulta4", formatarValor(dMulta4));
                        parametros.put("Dmulta5", formatarValor(dMulta5));
                        parametros.put("Dmulta6", formatarValor(dMulta6));
                        parametros.put("Dmulta7", formatarValor(dMulta7));
                        parametros.put("Dmulta8", formatarValor(dMulta8));
                        
                        parametros.put("Dcorremone1", formatarValor(dCorrecao1));
                        parametros.put("Dcorremone2", formatarValor(dCorrecao2));
                        parametros.put("Dcorremone3", formatarValor(dCorrecao3));
                        parametros.put("Dcorremone4", formatarValor(dCorrecao4));
                        parametros.put("Dcorremone5", formatarValor(dCorrecao5));
                        parametros.put("Dcorremone6", formatarValor(dCorrecao6));
                        parametros.put("Dcorremone7", formatarValor(dCorrecao7));
                        parametros.put("Dcorremone8", formatarValor(dCorrecao8));
                        
                        parametros.put("Djurosmota1", formatarValor(dJuros1));
                        parametros.put("Djurosmota2", formatarValor(dJuros2));
                        parametros.put("Djurosmota3", formatarValor(dJuros3));
                        parametros.put("Djurosmota4", formatarValor(dJuros4));
                        parametros.put("Djurosmota5", formatarValor(dJuros5));
                        parametros.put("Djurosmota6", formatarValor(dJuros6));
                        parametros.put("Djurosmota7", formatarValor(dJuros7));
                        parametros.put("Djurosmota8", formatarValor(dJuros8));
                        
                        parametros.put("Dtotal1", formatarValor(dTotal1));
                        parametros.put("Dtotal2", formatarValor(dTotal2));
                        parametros.put("Dtotal3", formatarValor(dTotal3));
                        parametros.put("Dtotal4", formatarValor(dTotal4));
                        parametros.put("Dtotal5", formatarValor(dTotal5));
                        parametros.put("Dtotal6", formatarValor(dTotal6));
                        parametros.put("Dtotal7", formatarValor(dTotal7));
                        parametros.put("Dtotal8", formatarValor(dTotal8));
                        
                        parametros.put("Dtotalencargos1", formatarValor(dTotalAtual1));
                        parametros.put("Dtotalencargos2", formatarValor(dTotalAtual2));
                        parametros.put("Dtotalencargos3", formatarValor(dTotalAtual3));
                        parametros.put("Dtotalencargos4", formatarValor(dTotalAtual4));
                        parametros.put("Dtotalencargos5", formatarValor(dTotalAtual5));
                        parametros.put("Dtotalencargos6", formatarValor(dTotalAtual6));
                        parametros.put("Dtotalencargos7", formatarValor(dTotalAtual7));
                        parametros.put("Dtotalencargos8", formatarValor(dTotalAtual8));
                        
                        parametros.put("Fcorrelacao1", fCorrecao1);
                        parametros.put("Fcorrelacao2", fCorrecao2);
                        parametros.put("Fcorrelacao3", fCorrecao3);
                        parametros.put("Fcorrelacao4", fCorrecao4);
                        parametros.put("Fcorrelacao5", fCorrecao5);
                        parametros.put("Fcorrelacao6", fCorrecao6);
                        parametros.put("Fcorrelacao7", fCorrecao7);
                        parametros.put("Fcorrelacao8", fCorrecao8);
                       
                        parametros.put("Ehonorario1", formatarValor(eHonorarios1));
                        parametros.put("Ehonorario2", formatarValor(eHonorarios2));
                        parametros.put("Ehonorario3", formatarValor(eHonorarios3));
                        parametros.put("Ehonorario4", formatarValor(eHonorarios4));
                        parametros.put("Ehonorario5", formatarValor(eHonorarios5));
                        parametros.put("Ehonorario6", formatarValor(eHonorarios6));
                        parametros.put("Ehonorario7", formatarValor(eHonorarios7));
                        parametros.put("Ehonorario8", formatarValor(eHonorarios8));
                        
                        parametros.put("Edespesa1", formatarValor(eDespesa1));
                        parametros.put("Edespesa2", formatarValor(eDespesa2));
                        parametros.put("Edespesa3", formatarValor(eDespesa3));
                        parametros.put("Edespesa4", formatarValor(eDespesa4));
                        parametros.put("Edespesa5", formatarValor(eDespesa5));
                        parametros.put("Edespesa6", formatarValor(eDespesa6));
                        parametros.put("Edespesa7", formatarValor(eDespesa7));
                        parametros.put("Edespesa8", formatarValor(eDespesa8));
                        
                        parametros.put("Fjuros1", fJuros1);
                        parametros.put("Fjuros2", fJuros2);
                        parametros.put("Fjuros3", fJuros3);
                        parametros.put("Fjuros4", fJuros4);
                        parametros.put("Fjuros5", fJuros5);
                        parametros.put("Fjuros6", fJuros6);
                        parametros.put("Fjuros7", fJuros7);
                        parametros.put("Fjuros8", fJuros8);
                        
                        parametros.put("Gcertidao", certAux);
                        
                        parametros.put("Valorfiscal1", formatarValor(tTotalInicial));
                        parametros.put("Valorfiscal2", formatarValor(tTotalAtualizado));
                        
                        //Montagem e passagem de parametros
                        JasperPrint print = JasperFillManager.fillReport(report, parametros,new JRBeanCollectionDataSource(assuntos));
                        //Exportação do relatório para PDF
                        JasperExportManager.exportReportToPdfFile(print, ("C://ImpressaoCDA/arquivos_gerados/")+certAux+"_certidao.pdf");
                        
//                        JasperViewer viewer = new JasperViewer(print, false);
//            
//                        viewer.setVisible(true);
//                        viewer.setTitle("Visualizar");

                        // limpa as variaveis para limpar as informações
                        nome = "";
                        cDataDef1 = cDataDef2 = cDataDef3 =cDataDef4 = cDataDef5 = cDataDef6 = cDataDef7 = cDataDef8 = "";
                        bData1=bData2=bData3=bData4=bData5=bData6=bData7=bData8="";
                        bNumero1=bNumero2=bNumero3=bNumero4=bNumero5=bNumero6=bNumero7=bNumero8="";
                        bOrdem1=bOrdem2=bOrdem3=bOrdem4=bOrdem5=bOrdem6=bOrdem7=bOrdem8="";
                        bNatureza1=bNatureza2=bNatureza3=bNatureza4=bNatureza5=bNatureza6=bNatureza7=bNatureza8="";
                        dPrincipal1=dPrincipal2=dPrincipal3=dPrincipal4=dPrincipal5=dPrincipal6=dPrincipal7=dPrincipal8="";
                        dMulta1=dMulta2=dMulta3=dMulta4=dMulta5=dMulta6=dMulta7=dMulta8="";
                        dCorrecao1=dCorrecao2=dCorrecao3=dCorrecao4=dCorrecao5=dCorrecao6=dCorrecao7=dCorrecao8="";
                        dJuros1=dJuros2=dJuros3=dJuros4=dJuros5=dJuros6=dJuros7=dJuros8="";
                        dTotal1=dTotal2=dTotal3=dTotal4=dTotal5=dTotal6=dTotal7=dTotal8="";
                        dTotalAtual1=dTotalAtual2=dTotalAtual3=dTotalAtual4=dTotalAtual5=dTotalAtual6=dTotalAtual7=dTotalAtual8="";
                        eDespesa1=eDespesa2=eDespesa3=eDespesa4=eDespesa5=eDespesa6=eDespesa7=eDespesa8="";
                        eHonorarios1=eHonorarios2=eHonorarios3=eHonorarios4=eHonorarios5=eHonorarios6=eHonorarios7=eHonorarios8="";
                        fCorrecao1=fCorrecao2=fCorrecao3=fCorrecao4=fCorrecao5=fCorrecao6=fCorrecao7=fCorrecao8="";
                        fJuros1=fJuros2=fJuros3=fJuros4=fJuros5=fJuros6=fJuros7=fJuros8="";
                        tTotalInicial=tTotalAtualizado="";
                        
                        
                    } catch (JRException ex) {
                        Logger.getLogger(GeraPdfArquivo.class.getName()).log(Level.SEVERE, null, ex);
                    }
            
                   
                   
                   System.out.println(certAux);
                   System.out.println(nome);
                   System.out.println(tTotalInicial);
                   certAux = certidao;
                }
                
                if(linha.substring(13, 14).equals("A")){
                    nome = nome+ "\n"+ linha.substring(18, 148);
//                    if(linha.substring(15, 17).equals("01")){
//                        nome = linha.substring(18,100);
//                    }
                }
                if(linha.substring(13, 14).equals("B")){
                    cDataDef1 = linha.substring(18,26);
                    cDataDef2 = linha.substring(27,35);
                    cDataDef3 = linha.substring(36,44);
                    cDataDef4 = linha.substring(45,53);
                    cDataDef5 = linha.substring(54,62);
                    cDataDef6 = linha.substring(63,71);
                    cDataDef7 = linha.substring(72,80);
                    cDataDef8 = linha.substring(81,89);
                }
                if(linha.substring(13, 14).equals("C")){
                    if(linha.substring(15, 17).equals("01")){
                        bNumero1 = linha.substring(18, 28);
                        bData1 = linha.substring(29, 37);
                        bOrdem1 = linha.substring(38, 56);
                        bNatureza1 = linha.substring(57, 110);
                    }else if(linha.substring(15, 17).equals("02")){
                        bNumero2 = linha.substring(18, 28);
                        bData2 = linha.substring(29, 37);
                        bOrdem2 = linha.substring(38, 56);
                        bNatureza2 = linha.substring(57, 110);
                    }else if(linha.substring(15, 17).equals("03")){
                        bNumero3 = linha.substring(18, 28);
                        bData3 = linha.substring(29, 37);
                        bOrdem3 = linha.substring(38, 56); 
                        bNatureza3 = linha.substring(57, 110);
                    }else if(linha.substring(15, 17).equals("04")){
                        bNumero4 = linha.substring(18, 28);
                        bData4 = linha.substring(29, 37);
                        bOrdem4 = linha.substring(38, 56);
                        bNatureza4 = linha.substring(57, 110);
                    }else if(linha.substring(15, 17).equals("05")){
                        bNumero5 = linha.substring(18, 28);
                        bData5 = linha.substring(29, 37);
                        bOrdem5 = linha.substring(38, 56);
                        bNatureza5 = linha.substring(57, 110);
                    }else if(linha.substring(15, 17).equals("06")){
                        bNumero6 = linha.substring(18, 28);
                        bData6 = linha.substring(29, 37);
                        bOrdem6 = linha.substring(38, 56);
                        bNatureza6 = linha.substring(57, 110);
                    }else if(linha.substring(15, 17).equals("07")){
                        bNumero7 = linha.substring(18, 28);
                        bData7 = linha.substring(29, 37);
                        bOrdem7 = linha.substring(38, 56);
                        bNatureza7 = linha.substring(57, 110);
                    }else if(linha.substring(15, 17).equals("08")){
                        bNumero8 = linha.substring(18, 28);
                        bData8 = linha.substring(29, 37);
                        bOrdem8 = linha.substring(38, 56);
                        bNatureza8 = linha.substring(57, 110);
                    }
                }
                if(linha.substring(13, 14).equals("D")){
                    if(linha.substring(15, 17).equals("01")){
                        dPrincipal1 = linha.substring(18, 32);
                        dMulta1 = linha.substring(33, 47);
                        dCorrecao1 = linha.substring(48, 62);
                        dJuros1 = linha.substring(63, 77);
                        dTotal1 = linha.substring(78, 92);
                        dTotalAtual1 = linha.substring(93, 107);
                    }else if(linha.substring(15, 17).equals("02")){
                        dPrincipal2 = linha.substring(18, 32);
                        dMulta2 = linha.substring(33, 47);
                        dCorrecao2 = linha.substring(48, 62);
                        dJuros2 = linha.substring(63, 77);
                        dTotal2 = linha.substring(78, 92);
                        dTotalAtual2 = linha.substring(93, 107);
                    }else if(linha.substring(15, 17).equals("03")){
                        dPrincipal3 = linha.substring(18, 32);
                        dMulta3 = linha.substring(33, 47);
                        dCorrecao3 = linha.substring(48, 62);
                        dJuros3 = linha.substring(63, 77);
                        dTotal3 = linha.substring(78, 92);
                        dTotalAtual3 = linha.substring(93, 107);
                    }else if(linha.substring(15, 17).equals("04")){
                        dPrincipal4 = linha.substring(18, 32);
                        dMulta4 = linha.substring(33, 47);
                        dCorrecao4 = linha.substring(48, 62);
                        dJuros4 = linha.substring(63, 77);
                        dTotal4 = linha.substring(78, 92);
                        dTotalAtual4 = linha.substring(93, 107);
                    }else if(linha.substring(15, 17).equals("05")){
                        dPrincipal5 = linha.substring(18, 32);
                        dMulta5 = linha.substring(33, 47);
                        dCorrecao5 = linha.substring(48, 62);
                        dJuros5 = linha.substring(63, 77);
                        dTotal5 = linha.substring(78, 92);
                        dTotalAtual5 = linha.substring(93, 107);
                    }else if(linha.substring(15, 17).equals("06")){
                        dPrincipal6 = linha.substring(18, 32);
                        dMulta6 = linha.substring(33, 47);
                        dCorrecao6 = linha.substring(48, 62);
                        dJuros6 = linha.substring(63, 77);
                        dTotal6 = linha.substring(78, 92);
                        dTotalAtual6 = linha.substring(93, 107);
                    }else if(linha.substring(15, 17).equals("07")){
                        dPrincipal7 = linha.substring(18, 32);
                        dMulta7 = linha.substring(33, 47);
                        dCorrecao7 = linha.substring(48, 62);
                        dJuros7 = linha.substring(63, 77);
                        dTotal7 = linha.substring(78, 92);
                        dTotalAtual7 = linha.substring(93, 107);
                    }else if(linha.substring(15, 17).equals("08")){
                        dPrincipal8 = linha.substring(18, 32);
                        dMulta8 = linha.substring(33, 47);
                        dCorrecao8 = linha.substring(48, 62);
                        dJuros8 = linha.substring(63, 77);
                        dTotal8 = linha.substring(78, 92);
                        dTotalAtual8 = linha.substring(93, 107);
                    }
                }
                
                if(linha.substring(13, 14).equals("E")){
                    if(linha.substring(15, 17).equals("01")){
                        eDespesa1 = linha.substring(18, 27);
                        eDespesa2 = linha.substring(28, 37);
                        eDespesa3 = linha.substring(38, 47);
                        eDespesa4 = linha.substring(48, 57);
                        eDespesa5 = linha.substring(58, 67);
                        eDespesa6 = linha.substring(68, 77);
                        eDespesa7 = linha.substring(78, 87);
                        eDespesa8 = linha.substring(88, 97);
                    }else if(linha.substring(15, 17).equals("02")){
                        eHonorarios1 = linha.substring(18, 29);
                        eHonorarios2 = linha.substring(30, 41);
                        eHonorarios3 = linha.substring(42, 53);
                        eHonorarios4 = linha.substring(54, 65);
                        eHonorarios5 = linha.substring(66, 77);
                        eHonorarios6 = linha.substring(78, 89);
                        eHonorarios7 = linha.substring(90, 101);
                        eHonorarios8 = linha.substring(102, 113);
                    }
                }
                
                if(linha.substring(13, 14).equals("F")){
                    if(linha.substring(15, 17).equals("01")){
                        fCorrecao1 = linha.substring(18, 26);
                        fCorrecao2 = linha.substring(27, 35);
                        fCorrecao3 = linha.substring(36, 44);
                        fCorrecao4 = linha.substring(45, 53);
                        fCorrecao5 = linha.substring(54, 62);
                        fCorrecao6 = linha.substring(63, 71);
                        fCorrecao7 = linha.substring(72, 80);
                        fCorrecao8 = linha.substring(81, 89);
                        
                    }
                    if(linha.substring(15, 17).equals("02")){
                        fJuros1 = linha.substring(18, 26);
                        fJuros2 = linha.substring(27, 35);
                        fJuros3 = linha.substring(36, 44);
                        fJuros4 = linha.substring(45, 53);
                        fJuros5 = linha.substring(54, 62);
                        fJuros6 = linha.substring(63, 71);
                        fJuros7 = linha.substring(72, 80);
                        fJuros8 = linha.substring(81, 89);
                    }
                }
                
                if(linha.substring(13, 14).equals("T")){
                    if(linha.substring(15, 17).equals("01")){
                         tTotalInicial = linha.substring(18, 32);
                         tTotalAtualizado = linha.substring(33, 47);
                    }
                }
                
                linha = b.readLine(); 
            }
            
            b.close();
            
            
        } catch (IOException e){
            e.printStackTrace();
            
        }
        
        this.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        JOptionPane.showMessageDialog(null,"processo finalizado");
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GeraPdfArquivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GeraPdfArquivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GeraPdfArquivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GeraPdfArquivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GeraPdfArquivo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Gerencia;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextFieldNomePasta;
    // End of variables declaration//GEN-END:variables
}
