/*
 * Generated by JasperReports - 05/04/19 14:34
 */
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.fill.*;

import java.util.*;
import java.math.*;
import java.text.*;
import java.io.*;
import java.net.*;



/**
 *
 */
public class certidao_final_1554485696517_464625 extends JREvaluator
{


    /**
     *
     */
    private JRFillParameter parameter_Djurosmota1 = null;
    private JRFillParameter parameter_Dcorremone6 = null;
    private JRFillParameter parameter_Djurosmota4 = null;
    private JRFillParameter parameter_Dcorremone7 = null;
    private JRFillParameter parameter_Djurosmota5 = null;
    private JRFillParameter parameter_Ehonorario1 = null;
    private JRFillParameter parameter_Djurosmota2 = null;
    private JRFillParameter parameter_Ehonorario2 = null;
    private JRFillParameter parameter_Dcorremone8 = null;
    private JRFillParameter parameter_Djurosmota3 = null;
    private JRFillParameter parameter_Ehonorario3 = null;
    private JRFillParameter parameter_Dcorremone2 = null;
    private JRFillParameter parameter_Ehonorario4 = null;
    private JRFillParameter parameter_Dcorremone3 = null;
    private JRFillParameter parameter_Ehonorario5 = null;
    private JRFillParameter parameter_Dcorremone4 = null;
    private JRFillParameter parameter_Ehonorario6 = null;
    private JRFillParameter parameter_Dcorremone5 = null;
    private JRFillParameter parameter_Ehonorario7 = null;
    private JRFillParameter parameter_Ehonorario8 = null;
    private JRFillParameter parameter_Dcorremone1 = null;
    private JRFillParameter parameter_Dtotalencargos1 = null;
    private JRFillParameter parameter_Dtotalencargos2 = null;
    private JRFillParameter parameter_Dtotalencargos3 = null;
    private JRFillParameter parameter_Dtotalencargos4 = null;
    private JRFillParameter parameter_Dtotalencargos5 = null;
    private JRFillParameter parameter_Dtotalencargos6 = null;
    private JRFillParameter parameter_Dtotalencargos7 = null;
    private JRFillParameter parameter_Dtotalencargos8 = null;
    private JRFillParameter parameter_Anome = null;
    private JRFillParameter parameter_REPORT_FILE_RESOLVER = null;
    private JRFillParameter parameter_REPORT_URL_HANDLER_FACTORY = null;
    private JRFillParameter parameter_REPORT_CONNECTION = null;
    private JRFillParameter parameter_JASPER_REPORT = null;
    private JRFillParameter parameter_REPORT_TIME_ZONE = null;
    private JRFillParameter parameter_REPORT_MAX_COUNT = null;
    private JRFillParameter parameter_REPORT_CLASS_LOADER = null;
    private JRFillParameter parameter_REPORT_VIRTUALIZER = null;
    private JRFillParameter parameter_Dprincipal8 = null;
    private JRFillParameter parameter_Dprincipal7 = null;
    private JRFillParameter parameter_Bdata8 = null;
    private JRFillParameter parameter_Dprincipal6 = null;
    private JRFillParameter parameter_Bdata6 = null;
    private JRFillParameter parameter_Dprincipal5 = null;
    private JRFillParameter parameter_Bdata7 = null;
    private JRFillParameter parameter_Dprincipal4 = null;
    private JRFillParameter parameter_Bdata4 = null;
    private JRFillParameter parameter_Dprincipal3 = null;
    private JRFillParameter parameter_Bdata5 = null;
    private JRFillParameter parameter_Dprincipal2 = null;
    private JRFillParameter parameter_Bdata2 = null;
    private JRFillParameter parameter_Dprincipal1 = null;
    private JRFillParameter parameter_Bdata3 = null;
    private JRFillParameter parameter_Bdata1 = null;
    private JRFillParameter parameter_REPORT_PARAMETERS_MAP = null;
    private JRFillParameter parameter_REPORT_DATA_SOURCE = null;
    private JRFillParameter parameter_Dmulta8 = null;
    private JRFillParameter parameter_Dmulta7 = null;
    private JRFillParameter parameter_Valorfiscal1 = null;
    private JRFillParameter parameter_Dmulta6 = null;
    private JRFillParameter parameter_Dmulta5 = null;
    private JRFillParameter parameter_REPORT_LOCALE = null;
    private JRFillParameter parameter_Fcorrelacao2 = null;
    private JRFillParameter parameter_Cdatadefi8 = null;
    private JRFillParameter parameter_Cdatadefi7 = null;
    private JRFillParameter parameter_Fcorrelacao1 = null;
    private JRFillParameter parameter_Cdatadefi6 = null;
    private JRFillParameter parameter_Fcorrelacao4 = null;
    private JRFillParameter parameter_Cdatadefi5 = null;
    private JRFillParameter parameter_Fcorrelacao3 = null;
    private JRFillParameter parameter_Cdatadefi4 = null;
    private JRFillParameter parameter_Dmulta4 = null;
    private JRFillParameter parameter_Fcorrelacao6 = null;
    private JRFillParameter parameter_Cdatadefi3 = null;
    private JRFillParameter parameter_Dmulta3 = null;
    private JRFillParameter parameter_Fcorrelacao5 = null;
    private JRFillParameter parameter_Cdatadefi2 = null;
    private JRFillParameter parameter_Dmulta2 = null;
    private JRFillParameter parameter_Fcorrelacao8 = null;
    private JRFillParameter parameter_Cdatadefi1 = null;
    private JRFillParameter parameter_Dmulta1 = null;
    private JRFillParameter parameter_Fcorrelacao7 = null;
    private JRFillParameter parameter_JASPER_REPORTS_CONTEXT = null;
    private JRFillParameter parameter_REPORT_FORMAT_FACTORY = null;
    private JRFillParameter parameter_Valorfiscal2 = null;
    private JRFillParameter parameter_Bnumero1 = null;
    private JRFillParameter parameter_Bnumero3 = null;
    private JRFillParameter parameter_Bnumero2 = null;
    private JRFillParameter parameter_Bnumero5 = null;
    private JRFillParameter parameter_Bnumero4 = null;
    private JRFillParameter parameter_Bnumero7 = null;
    private JRFillParameter parameter_Bnumero6 = null;
    private JRFillParameter parameter_REPORT_TEMPLATES = null;
    private JRFillParameter parameter_Bnumero8 = null;
    private JRFillParameter parameter_Fjuros5 = null;
    private JRFillParameter parameter_Fjuros6 = null;
    private JRFillParameter parameter_REPORT_SCRIPTLET = null;
    private JRFillParameter parameter_Fjuros7 = null;
    private JRFillParameter parameter_Fjuros8 = null;
    private JRFillParameter parameter_Edespesa4 = null;
    private JRFillParameter parameter_Fjuros1 = null;
    private JRFillParameter parameter_Edespesa5 = null;
    private JRFillParameter parameter_Fjuros2 = null;
    private JRFillParameter parameter_Edespesa6 = null;
    private JRFillParameter parameter_Fjuros3 = null;
    private JRFillParameter parameter_Edespesa7 = null;
    private JRFillParameter parameter_Fjuros4 = null;
    private JRFillParameter parameter_Dtotal8 = null;
    private JRFillParameter parameter_Edespesa1 = null;
    private JRFillParameter parameter_REPORT_RESOURCE_BUNDLE = null;
    private JRFillParameter parameter_Edespesa2 = null;
    private JRFillParameter parameter_Edespesa3 = null;
    private JRFillParameter parameter_Dtotal4 = null;
    private JRFillParameter parameter_Dtotal5 = null;
    private JRFillParameter parameter_Dtotal6 = null;
    private JRFillParameter parameter_Dtotal7 = null;
    private JRFillParameter parameter_SORT_FIELDS = null;
    private JRFillParameter parameter_Edespesa8 = null;
    private JRFillParameter parameter_Dtotal1 = null;
    private JRFillParameter parameter_Dtotal2 = null;
    private JRFillParameter parameter_Dtotal3 = null;
    private JRFillParameter parameter_IS_IGNORE_PAGINATION = null;
    private JRFillParameter parameter_FILTER = null;
    private JRFillParameter parameter_Bordem7 = null;
    private JRFillParameter parameter_Bordem8 = null;
    private JRFillParameter parameter_Bordem1 = null;
    private JRFillParameter parameter_Bnatureza8 = null;
    private JRFillParameter parameter_Bordem2 = null;
    private JRFillParameter parameter_Bordem5 = null;
    private JRFillParameter parameter_Gcertidao = null;
    private JRFillParameter parameter_Bordem6 = null;
    private JRFillParameter parameter_Bordem3 = null;
    private JRFillParameter parameter_Bordem4 = null;
    private JRFillParameter parameter_Djurosmota8 = null;
    private JRFillParameter parameter_Bnatureza1 = null;
    private JRFillParameter parameter_Parameter9 = null;
    private JRFillParameter parameter_Bnatureza2 = null;
    private JRFillParameter parameter_Djurosmota6 = null;
    private JRFillParameter parameter_REPORT_CONTEXT = null;
    private JRFillParameter parameter_Bnatureza3 = null;
    private JRFillParameter parameter_Djurosmota7 = null;
    private JRFillParameter parameter_Bnatureza4 = null;
    private JRFillParameter parameter_Bnatureza5 = null;
    private JRFillParameter parameter_Bnatureza6 = null;
    private JRFillParameter parameter_Bnatureza7 = null;
    private JRFillVariable variable_PAGE_NUMBER = null;
    private JRFillVariable variable_COLUMN_NUMBER = null;
    private JRFillVariable variable_REPORT_COUNT = null;
    private JRFillVariable variable_PAGE_COUNT = null;
    private JRFillVariable variable_COLUMN_COUNT = null;


    /**
     *
     */
    public void customizedInit(
        Map pm,
        Map fm,
        Map vm
        )
    {
        initParams(pm);
        initFields(fm);
        initVars(vm);
    }


    /**
     *
     */
    private void initParams(Map pm)
    {
        parameter_Djurosmota1 = (JRFillParameter)pm.get("Djurosmota1");
        parameter_Dcorremone6 = (JRFillParameter)pm.get("Dcorremone6");
        parameter_Djurosmota4 = (JRFillParameter)pm.get("Djurosmota4");
        parameter_Dcorremone7 = (JRFillParameter)pm.get("Dcorremone7");
        parameter_Djurosmota5 = (JRFillParameter)pm.get("Djurosmota5");
        parameter_Ehonorario1 = (JRFillParameter)pm.get("Ehonorario1");
        parameter_Djurosmota2 = (JRFillParameter)pm.get("Djurosmota2");
        parameter_Ehonorario2 = (JRFillParameter)pm.get("Ehonorario2");
        parameter_Dcorremone8 = (JRFillParameter)pm.get("Dcorremone8");
        parameter_Djurosmota3 = (JRFillParameter)pm.get("Djurosmota3");
        parameter_Ehonorario3 = (JRFillParameter)pm.get("Ehonorario3");
        parameter_Dcorremone2 = (JRFillParameter)pm.get("Dcorremone2");
        parameter_Ehonorario4 = (JRFillParameter)pm.get("Ehonorario4");
        parameter_Dcorremone3 = (JRFillParameter)pm.get("Dcorremone3");
        parameter_Ehonorario5 = (JRFillParameter)pm.get("Ehonorario5");
        parameter_Dcorremone4 = (JRFillParameter)pm.get("Dcorremone4");
        parameter_Ehonorario6 = (JRFillParameter)pm.get("Ehonorario6");
        parameter_Dcorremone5 = (JRFillParameter)pm.get("Dcorremone5");
        parameter_Ehonorario7 = (JRFillParameter)pm.get("Ehonorario7");
        parameter_Ehonorario8 = (JRFillParameter)pm.get("Ehonorario8");
        parameter_Dcorremone1 = (JRFillParameter)pm.get("Dcorremone1");
        parameter_Dtotalencargos1 = (JRFillParameter)pm.get("Dtotalencargos1");
        parameter_Dtotalencargos2 = (JRFillParameter)pm.get("Dtotalencargos2");
        parameter_Dtotalencargos3 = (JRFillParameter)pm.get("Dtotalencargos3");
        parameter_Dtotalencargos4 = (JRFillParameter)pm.get("Dtotalencargos4");
        parameter_Dtotalencargos5 = (JRFillParameter)pm.get("Dtotalencargos5");
        parameter_Dtotalencargos6 = (JRFillParameter)pm.get("Dtotalencargos6");
        parameter_Dtotalencargos7 = (JRFillParameter)pm.get("Dtotalencargos7");
        parameter_Dtotalencargos8 = (JRFillParameter)pm.get("Dtotalencargos8");
        parameter_Anome = (JRFillParameter)pm.get("Anome");
        parameter_REPORT_FILE_RESOLVER = (JRFillParameter)pm.get("REPORT_FILE_RESOLVER");
        parameter_REPORT_URL_HANDLER_FACTORY = (JRFillParameter)pm.get("REPORT_URL_HANDLER_FACTORY");
        parameter_REPORT_CONNECTION = (JRFillParameter)pm.get("REPORT_CONNECTION");
        parameter_JASPER_REPORT = (JRFillParameter)pm.get("JASPER_REPORT");
        parameter_REPORT_TIME_ZONE = (JRFillParameter)pm.get("REPORT_TIME_ZONE");
        parameter_REPORT_MAX_COUNT = (JRFillParameter)pm.get("REPORT_MAX_COUNT");
        parameter_REPORT_CLASS_LOADER = (JRFillParameter)pm.get("REPORT_CLASS_LOADER");
        parameter_REPORT_VIRTUALIZER = (JRFillParameter)pm.get("REPORT_VIRTUALIZER");
        parameter_Dprincipal8 = (JRFillParameter)pm.get("Dprincipal8");
        parameter_Dprincipal7 = (JRFillParameter)pm.get("Dprincipal7");
        parameter_Bdata8 = (JRFillParameter)pm.get("Bdata8");
        parameter_Dprincipal6 = (JRFillParameter)pm.get("Dprincipal6");
        parameter_Bdata6 = (JRFillParameter)pm.get("Bdata6");
        parameter_Dprincipal5 = (JRFillParameter)pm.get("Dprincipal5");
        parameter_Bdata7 = (JRFillParameter)pm.get("Bdata7");
        parameter_Dprincipal4 = (JRFillParameter)pm.get("Dprincipal4");
        parameter_Bdata4 = (JRFillParameter)pm.get("Bdata4");
        parameter_Dprincipal3 = (JRFillParameter)pm.get("Dprincipal3");
        parameter_Bdata5 = (JRFillParameter)pm.get("Bdata5");
        parameter_Dprincipal2 = (JRFillParameter)pm.get("Dprincipal2");
        parameter_Bdata2 = (JRFillParameter)pm.get("Bdata2");
        parameter_Dprincipal1 = (JRFillParameter)pm.get("Dprincipal1");
        parameter_Bdata3 = (JRFillParameter)pm.get("Bdata3");
        parameter_Bdata1 = (JRFillParameter)pm.get("Bdata1");
        parameter_REPORT_PARAMETERS_MAP = (JRFillParameter)pm.get("REPORT_PARAMETERS_MAP");
        parameter_REPORT_DATA_SOURCE = (JRFillParameter)pm.get("REPORT_DATA_SOURCE");
        parameter_Dmulta8 = (JRFillParameter)pm.get("Dmulta8");
        parameter_Dmulta7 = (JRFillParameter)pm.get("Dmulta7");
        parameter_Valorfiscal1 = (JRFillParameter)pm.get("Valorfiscal1");
        parameter_Dmulta6 = (JRFillParameter)pm.get("Dmulta6");
        parameter_Dmulta5 = (JRFillParameter)pm.get("Dmulta5");
        parameter_REPORT_LOCALE = (JRFillParameter)pm.get("REPORT_LOCALE");
        parameter_Fcorrelacao2 = (JRFillParameter)pm.get("Fcorrelacao2");
        parameter_Cdatadefi8 = (JRFillParameter)pm.get("Cdatadefi8");
        parameter_Cdatadefi7 = (JRFillParameter)pm.get("Cdatadefi7");
        parameter_Fcorrelacao1 = (JRFillParameter)pm.get("Fcorrelacao1");
        parameter_Cdatadefi6 = (JRFillParameter)pm.get("Cdatadefi6");
        parameter_Fcorrelacao4 = (JRFillParameter)pm.get("Fcorrelacao4");
        parameter_Cdatadefi5 = (JRFillParameter)pm.get("Cdatadefi5");
        parameter_Fcorrelacao3 = (JRFillParameter)pm.get("Fcorrelacao3");
        parameter_Cdatadefi4 = (JRFillParameter)pm.get("Cdatadefi4");
        parameter_Dmulta4 = (JRFillParameter)pm.get("Dmulta4");
        parameter_Fcorrelacao6 = (JRFillParameter)pm.get("Fcorrelacao6");
        parameter_Cdatadefi3 = (JRFillParameter)pm.get("Cdatadefi3");
        parameter_Dmulta3 = (JRFillParameter)pm.get("Dmulta3");
        parameter_Fcorrelacao5 = (JRFillParameter)pm.get("Fcorrelacao5");
        parameter_Cdatadefi2 = (JRFillParameter)pm.get("Cdatadefi2");
        parameter_Dmulta2 = (JRFillParameter)pm.get("Dmulta2");
        parameter_Fcorrelacao8 = (JRFillParameter)pm.get("Fcorrelacao8");
        parameter_Cdatadefi1 = (JRFillParameter)pm.get("Cdatadefi1");
        parameter_Dmulta1 = (JRFillParameter)pm.get("Dmulta1");
        parameter_Fcorrelacao7 = (JRFillParameter)pm.get("Fcorrelacao7");
        parameter_JASPER_REPORTS_CONTEXT = (JRFillParameter)pm.get("JASPER_REPORTS_CONTEXT");
        parameter_REPORT_FORMAT_FACTORY = (JRFillParameter)pm.get("REPORT_FORMAT_FACTORY");
        parameter_Valorfiscal2 = (JRFillParameter)pm.get("Valorfiscal2");
        parameter_Bnumero1 = (JRFillParameter)pm.get("Bnumero1");
        parameter_Bnumero3 = (JRFillParameter)pm.get("Bnumero3");
        parameter_Bnumero2 = (JRFillParameter)pm.get("Bnumero2");
        parameter_Bnumero5 = (JRFillParameter)pm.get("Bnumero5");
        parameter_Bnumero4 = (JRFillParameter)pm.get("Bnumero4");
        parameter_Bnumero7 = (JRFillParameter)pm.get("Bnumero7");
        parameter_Bnumero6 = (JRFillParameter)pm.get("Bnumero6");
        parameter_REPORT_TEMPLATES = (JRFillParameter)pm.get("REPORT_TEMPLATES");
        parameter_Bnumero8 = (JRFillParameter)pm.get("Bnumero8");
        parameter_Fjuros5 = (JRFillParameter)pm.get("Fjuros5");
        parameter_Fjuros6 = (JRFillParameter)pm.get("Fjuros6");
        parameter_REPORT_SCRIPTLET = (JRFillParameter)pm.get("REPORT_SCRIPTLET");
        parameter_Fjuros7 = (JRFillParameter)pm.get("Fjuros7");
        parameter_Fjuros8 = (JRFillParameter)pm.get("Fjuros8");
        parameter_Edespesa4 = (JRFillParameter)pm.get("Edespesa4");
        initParams1(pm);
    }


    /**
     *
     */
    private void initParams1(Map pm)
    {
        parameter_Fjuros1 = (JRFillParameter)pm.get("Fjuros1");
        parameter_Edespesa5 = (JRFillParameter)pm.get("Edespesa5");
        parameter_Fjuros2 = (JRFillParameter)pm.get("Fjuros2");
        parameter_Edespesa6 = (JRFillParameter)pm.get("Edespesa6");
        parameter_Fjuros3 = (JRFillParameter)pm.get("Fjuros3");
        parameter_Edespesa7 = (JRFillParameter)pm.get("Edespesa7");
        parameter_Fjuros4 = (JRFillParameter)pm.get("Fjuros4");
        parameter_Dtotal8 = (JRFillParameter)pm.get("Dtotal8");
        parameter_Edespesa1 = (JRFillParameter)pm.get("Edespesa1");
        parameter_REPORT_RESOURCE_BUNDLE = (JRFillParameter)pm.get("REPORT_RESOURCE_BUNDLE");
        parameter_Edespesa2 = (JRFillParameter)pm.get("Edespesa2");
        parameter_Edespesa3 = (JRFillParameter)pm.get("Edespesa3");
        parameter_Dtotal4 = (JRFillParameter)pm.get("Dtotal4");
        parameter_Dtotal5 = (JRFillParameter)pm.get("Dtotal5");
        parameter_Dtotal6 = (JRFillParameter)pm.get("Dtotal6");
        parameter_Dtotal7 = (JRFillParameter)pm.get("Dtotal7");
        parameter_SORT_FIELDS = (JRFillParameter)pm.get("SORT_FIELDS");
        parameter_Edespesa8 = (JRFillParameter)pm.get("Edespesa8");
        parameter_Dtotal1 = (JRFillParameter)pm.get("Dtotal1");
        parameter_Dtotal2 = (JRFillParameter)pm.get("Dtotal2");
        parameter_Dtotal3 = (JRFillParameter)pm.get("Dtotal3");
        parameter_IS_IGNORE_PAGINATION = (JRFillParameter)pm.get("IS_IGNORE_PAGINATION");
        parameter_FILTER = (JRFillParameter)pm.get("FILTER");
        parameter_Bordem7 = (JRFillParameter)pm.get("Bordem7");
        parameter_Bordem8 = (JRFillParameter)pm.get("Bordem8");
        parameter_Bordem1 = (JRFillParameter)pm.get("Bordem1");
        parameter_Bnatureza8 = (JRFillParameter)pm.get("Bnatureza8");
        parameter_Bordem2 = (JRFillParameter)pm.get("Bordem2");
        parameter_Bordem5 = (JRFillParameter)pm.get("Bordem5");
        parameter_Gcertidao = (JRFillParameter)pm.get("Gcertidao");
        parameter_Bordem6 = (JRFillParameter)pm.get("Bordem6");
        parameter_Bordem3 = (JRFillParameter)pm.get("Bordem3");
        parameter_Bordem4 = (JRFillParameter)pm.get("Bordem4");
        parameter_Djurosmota8 = (JRFillParameter)pm.get("Djurosmota8");
        parameter_Bnatureza1 = (JRFillParameter)pm.get("Bnatureza1");
        parameter_Parameter9 = (JRFillParameter)pm.get("Parameter9");
        parameter_Bnatureza2 = (JRFillParameter)pm.get("Bnatureza2");
        parameter_Djurosmota6 = (JRFillParameter)pm.get("Djurosmota6");
        parameter_REPORT_CONTEXT = (JRFillParameter)pm.get("REPORT_CONTEXT");
        parameter_Bnatureza3 = (JRFillParameter)pm.get("Bnatureza3");
        parameter_Djurosmota7 = (JRFillParameter)pm.get("Djurosmota7");
        parameter_Bnatureza4 = (JRFillParameter)pm.get("Bnatureza4");
        parameter_Bnatureza5 = (JRFillParameter)pm.get("Bnatureza5");
        parameter_Bnatureza6 = (JRFillParameter)pm.get("Bnatureza6");
        parameter_Bnatureza7 = (JRFillParameter)pm.get("Bnatureza7");
    }


    /**
     *
     */
    private void initFields(Map fm)
    {
    }


    /**
     *
     */
    private void initVars(Map vm)
    {
        variable_PAGE_NUMBER = (JRFillVariable)vm.get("PAGE_NUMBER");
        variable_COLUMN_NUMBER = (JRFillVariable)vm.get("COLUMN_NUMBER");
        variable_REPORT_COUNT = (JRFillVariable)vm.get("REPORT_COUNT");
        variable_PAGE_COUNT = (JRFillVariable)vm.get("PAGE_COUNT");
        variable_COLUMN_COUNT = (JRFillVariable)vm.get("COLUMN_COUNT");
    }


    /**
     *
     */
    public Object evaluate(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=0$
                break;
            }
            case 1 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=1$
                break;
            }
            case 2 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=2$
                break;
            }
            case 3 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=3$
                break;
            }
            case 4 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=4$
                break;
            }
            case 5 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=5$
                break;
            }
            case 6 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=6$
                break;
            }
            case 7 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=7$
                break;
            }
            case 8 : 
            {
                value = ((java.lang.String)parameter_Anome.getValue()); //$JR_EXPR_ID=8$
                break;
            }
            case 9 : 
            {
                value = ((java.lang.String)parameter_Bnumero1.getValue()); //$JR_EXPR_ID=9$
                break;
            }
            case 10 : 
            {
                value = ((java.lang.String)parameter_Bnumero2.getValue()); //$JR_EXPR_ID=10$
                break;
            }
            case 11 : 
            {
                value = ((java.lang.String)parameter_Bnumero3.getValue()); //$JR_EXPR_ID=11$
                break;
            }
            case 12 : 
            {
                value = ((java.lang.String)parameter_Bnumero4.getValue()); //$JR_EXPR_ID=12$
                break;
            }
            case 13 : 
            {
                value = ((java.lang.String)parameter_Bnumero5.getValue()); //$JR_EXPR_ID=13$
                break;
            }
            case 14 : 
            {
                value = ((java.lang.String)parameter_Bdata1.getValue()); //$JR_EXPR_ID=14$
                break;
            }
            case 15 : 
            {
                value = ((java.lang.String)parameter_Bdata2.getValue()); //$JR_EXPR_ID=15$
                break;
            }
            case 16 : 
            {
                value = ((java.lang.String)parameter_Bdata3.getValue()); //$JR_EXPR_ID=16$
                break;
            }
            case 17 : 
            {
                value = ((java.lang.String)parameter_Bdata4.getValue()); //$JR_EXPR_ID=17$
                break;
            }
            case 18 : 
            {
                value = ((java.lang.String)parameter_Bdata5.getValue()); //$JR_EXPR_ID=18$
                break;
            }
            case 19 : 
            {
                value = ((java.lang.String)parameter_Bdata6.getValue()); //$JR_EXPR_ID=19$
                break;
            }
            case 20 : 
            {
                value = ((java.lang.String)parameter_Bdata7.getValue()); //$JR_EXPR_ID=20$
                break;
            }
            case 21 : 
            {
                value = ((java.lang.String)parameter_Bordem1.getValue()); //$JR_EXPR_ID=21$
                break;
            }
            case 22 : 
            {
                value = ((java.lang.String)parameter_Bordem2.getValue()); //$JR_EXPR_ID=22$
                break;
            }
            case 23 : 
            {
                value = ((java.lang.String)parameter_Bordem3.getValue()); //$JR_EXPR_ID=23$
                break;
            }
            case 24 : 
            {
                value = ((java.lang.String)parameter_Bordem5.getValue()); //$JR_EXPR_ID=24$
                break;
            }
            case 25 : 
            {
                value = ((java.lang.String)parameter_Bordem6.getValue()); //$JR_EXPR_ID=25$
                break;
            }
            case 26 : 
            {
                value = ((java.lang.String)parameter_Bordem7.getValue()); //$JR_EXPR_ID=26$
                break;
            }
            case 27 : 
            {
                value = ((java.lang.String)parameter_Bnatureza1.getValue()); //$JR_EXPR_ID=27$
                break;
            }
            case 28 : 
            {
                value = ((java.lang.String)parameter_Bnatureza2.getValue()); //$JR_EXPR_ID=28$
                break;
            }
            case 29 : 
            {
                value = ((java.lang.String)parameter_Bnatureza3.getValue()); //$JR_EXPR_ID=29$
                break;
            }
            case 30 : 
            {
                value = ((java.lang.String)parameter_Bnatureza4.getValue()); //$JR_EXPR_ID=30$
                break;
            }
            case 31 : 
            {
                value = ((java.lang.String)parameter_Bnatureza5.getValue()); //$JR_EXPR_ID=31$
                break;
            }
            case 32 : 
            {
                value = ((java.lang.String)parameter_Bnatureza6.getValue()); //$JR_EXPR_ID=32$
                break;
            }
            case 33 : 
            {
                value = ((java.lang.String)parameter_Bnatureza7.getValue()); //$JR_EXPR_ID=33$
                break;
            }
            case 34 : 
            {
                value = ((java.lang.String)parameter_Cdatadefi1.getValue()); //$JR_EXPR_ID=34$
                break;
            }
            case 35 : 
            {
                value = ((java.lang.String)parameter_Cdatadefi2.getValue()); //$JR_EXPR_ID=35$
                break;
            }
            case 36 : 
            {
                value = ((java.lang.String)parameter_Cdatadefi3.getValue()); //$JR_EXPR_ID=36$
                break;
            }
            case 37 : 
            {
                value = ((java.lang.String)parameter_Cdatadefi4.getValue()); //$JR_EXPR_ID=37$
                break;
            }
            case 38 : 
            {
                value = ((java.lang.String)parameter_Cdatadefi5.getValue()); //$JR_EXPR_ID=38$
                break;
            }
            case 39 : 
            {
                value = ((java.lang.String)parameter_Cdatadefi6.getValue()); //$JR_EXPR_ID=39$
                break;
            }
            case 40 : 
            {
                value = ((java.lang.String)parameter_Cdatadefi7.getValue()); //$JR_EXPR_ID=40$
                break;
            }
            case 41 : 
            {
                value = ((java.lang.String)parameter_Dprincipal1.getValue()); //$JR_EXPR_ID=41$
                break;
            }
            case 42 : 
            {
                value = ((java.lang.String)parameter_Dprincipal2.getValue()); //$JR_EXPR_ID=42$
                break;
            }
            case 43 : 
            {
                value = ((java.lang.String)parameter_Dprincipal3.getValue()); //$JR_EXPR_ID=43$
                break;
            }
            case 44 : 
            {
                value = ((java.lang.String)parameter_Dprincipal4.getValue()); //$JR_EXPR_ID=44$
                break;
            }
            case 45 : 
            {
                value = ((java.lang.String)parameter_Dprincipal5.getValue()); //$JR_EXPR_ID=45$
                break;
            }
            case 46 : 
            {
                value = ((java.lang.String)parameter_Dprincipal6.getValue()); //$JR_EXPR_ID=46$
                break;
            }
            case 47 : 
            {
                value = ((java.lang.String)parameter_Dprincipal7.getValue()); //$JR_EXPR_ID=47$
                break;
            }
            case 48 : 
            {
                value = ((java.lang.String)parameter_Dmulta1.getValue()); //$JR_EXPR_ID=48$
                break;
            }
            case 49 : 
            {
                value = ((java.lang.String)parameter_Dmulta2.getValue()); //$JR_EXPR_ID=49$
                break;
            }
            case 50 : 
            {
                value = ((java.lang.String)parameter_Dmulta3.getValue()); //$JR_EXPR_ID=50$
                break;
            }
            case 51 : 
            {
                value = ((java.lang.String)parameter_Dmulta4.getValue()); //$JR_EXPR_ID=51$
                break;
            }
            case 52 : 
            {
                value = ((java.lang.String)parameter_Dmulta5.getValue()); //$JR_EXPR_ID=52$
                break;
            }
            case 53 : 
            {
                value = ((java.lang.String)parameter_Dmulta6.getValue()); //$JR_EXPR_ID=53$
                break;
            }
            case 54 : 
            {
                value = ((java.lang.String)parameter_Dmulta7.getValue()); //$JR_EXPR_ID=54$
                break;
            }
            case 55 : 
            {
                value = ((java.lang.String)parameter_Dcorremone1.getValue()); //$JR_EXPR_ID=55$
                break;
            }
            case 56 : 
            {
                value = ((java.lang.String)parameter_Dcorremone2.getValue()); //$JR_EXPR_ID=56$
                break;
            }
            case 57 : 
            {
                value = ((java.lang.String)parameter_Dcorremone3.getValue()); //$JR_EXPR_ID=57$
                break;
            }
            case 58 : 
            {
                value = ((java.lang.String)parameter_Dcorremone4.getValue()); //$JR_EXPR_ID=58$
                break;
            }
            case 59 : 
            {
                value = ((java.lang.String)parameter_Dcorremone5.getValue()); //$JR_EXPR_ID=59$
                break;
            }
            case 60 : 
            {
                value = ((java.lang.String)parameter_Dcorremone6.getValue()); //$JR_EXPR_ID=60$
                break;
            }
            case 61 : 
            {
                value = ((java.lang.String)parameter_Dcorremone7.getValue()); //$JR_EXPR_ID=61$
                break;
            }
            case 62 : 
            {
                value = ((java.lang.String)parameter_Djurosmota1.getValue()); //$JR_EXPR_ID=62$
                break;
            }
            case 63 : 
            {
                value = ((java.lang.String)parameter_Djurosmota2.getValue()); //$JR_EXPR_ID=63$
                break;
            }
            case 64 : 
            {
                value = ((java.lang.String)parameter_Djurosmota3.getValue()); //$JR_EXPR_ID=64$
                break;
            }
            case 65 : 
            {
                value = ((java.lang.String)parameter_Djurosmota4.getValue()); //$JR_EXPR_ID=65$
                break;
            }
            case 66 : 
            {
                value = ((java.lang.String)parameter_Djurosmota5.getValue()); //$JR_EXPR_ID=66$
                break;
            }
            case 67 : 
            {
                value = ((java.lang.String)parameter_Djurosmota6.getValue()); //$JR_EXPR_ID=67$
                break;
            }
            case 68 : 
            {
                value = ((java.lang.String)parameter_Djurosmota7.getValue()); //$JR_EXPR_ID=68$
                break;
            }
            case 69 : 
            {
                value = ((java.lang.String)parameter_Dtotal1.getValue()); //$JR_EXPR_ID=69$
                break;
            }
            case 70 : 
            {
                value = ((java.lang.String)parameter_Dtotal2.getValue()); //$JR_EXPR_ID=70$
                break;
            }
            case 71 : 
            {
                value = ((java.lang.String)parameter_Dtotal3.getValue()); //$JR_EXPR_ID=71$
                break;
            }
            case 72 : 
            {
                value = ((java.lang.String)parameter_Dtotal4.getValue()); //$JR_EXPR_ID=72$
                break;
            }
            case 73 : 
            {
                value = ((java.lang.String)parameter_Dtotal5.getValue()); //$JR_EXPR_ID=73$
                break;
            }
            case 74 : 
            {
                value = ((java.lang.String)parameter_Dtotal6.getValue()); //$JR_EXPR_ID=74$
                break;
            }
            case 75 : 
            {
                value = ((java.lang.String)parameter_Dtotal7.getValue()); //$JR_EXPR_ID=75$
                break;
            }
            case 76 : 
            {
                value = ((java.lang.String)parameter_Dtotalencargos1.getValue()); //$JR_EXPR_ID=76$
                break;
            }
            case 77 : 
            {
                value = ((java.lang.String)parameter_Dtotalencargos2.getValue()); //$JR_EXPR_ID=77$
                break;
            }
            case 78 : 
            {
                value = ((java.lang.String)parameter_Dtotalencargos3.getValue()); //$JR_EXPR_ID=78$
                break;
            }
            case 79 : 
            {
                value = ((java.lang.String)parameter_Dtotalencargos4.getValue()); //$JR_EXPR_ID=79$
                break;
            }
            case 80 : 
            {
                value = ((java.lang.String)parameter_Dtotalencargos5.getValue()); //$JR_EXPR_ID=80$
                break;
            }
            case 81 : 
            {
                value = ((java.lang.String)parameter_Dtotalencargos6.getValue()); //$JR_EXPR_ID=81$
                break;
            }
            case 82 : 
            {
                value = ((java.lang.String)parameter_Dtotalencargos7.getValue()); //$JR_EXPR_ID=82$
                break;
            }
            case 83 : 
            {
                value = ((java.lang.String)parameter_Ehonorario1.getValue()); //$JR_EXPR_ID=83$
                break;
            }
            case 84 : 
            {
                value = ((java.lang.String)parameter_Ehonorario2.getValue()); //$JR_EXPR_ID=84$
                break;
            }
            case 85 : 
            {
                value = ((java.lang.String)parameter_Ehonorario3.getValue()); //$JR_EXPR_ID=85$
                break;
            }
            case 86 : 
            {
                value = ((java.lang.String)parameter_Ehonorario4.getValue()); //$JR_EXPR_ID=86$
                break;
            }
            case 87 : 
            {
                value = ((java.lang.String)parameter_Ehonorario5.getValue()); //$JR_EXPR_ID=87$
                break;
            }
            case 88 : 
            {
                value = ((java.lang.String)parameter_Ehonorario6.getValue()); //$JR_EXPR_ID=88$
                break;
            }
            case 89 : 
            {
                value = ((java.lang.String)parameter_Ehonorario7.getValue()); //$JR_EXPR_ID=89$
                break;
            }
            case 90 : 
            {
                value = ((java.lang.String)parameter_Ehonorario8.getValue()); //$JR_EXPR_ID=90$
                break;
            }
            case 91 : 
            {
                value = ((java.lang.String)parameter_Edespesa1.getValue()); //$JR_EXPR_ID=91$
                break;
            }
            case 92 : 
            {
                value = ((java.lang.String)parameter_Edespesa2.getValue()); //$JR_EXPR_ID=92$
                break;
            }
            case 93 : 
            {
                value = ((java.lang.String)parameter_Edespesa3.getValue()); //$JR_EXPR_ID=93$
                break;
            }
            case 94 : 
            {
                value = ((java.lang.String)parameter_Edespesa4.getValue()); //$JR_EXPR_ID=94$
                break;
            }
            case 95 : 
            {
                value = ((java.lang.String)parameter_Edespesa5.getValue()); //$JR_EXPR_ID=95$
                break;
            }
            case 96 : 
            {
                value = ((java.lang.String)parameter_Edespesa6.getValue()); //$JR_EXPR_ID=96$
                break;
            }
            case 97 : 
            {
                value = ((java.lang.String)parameter_Edespesa7.getValue()); //$JR_EXPR_ID=97$
                break;
            }
            case 98 : 
            {
                value = ((java.lang.String)parameter_Edespesa8.getValue()); //$JR_EXPR_ID=98$
                break;
            }
            case 99 : 
            {
                value = ((java.lang.String)parameter_Fcorrelacao1.getValue()); //$JR_EXPR_ID=99$
                break;
            }
           default :
           {
               value = evaluate1(id);
           }
        }
        
        return value;
    }


    /**
     *
     */
    private Object evaluate1(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 100 : 
            {
                value = ((java.lang.String)parameter_Fcorrelacao2.getValue()); //$JR_EXPR_ID=100$
                break;
            }
            case 101 : 
            {
                value = ((java.lang.String)parameter_Fcorrelacao3.getValue()); //$JR_EXPR_ID=101$
                break;
            }
            case 102 : 
            {
                value = ((java.lang.String)parameter_Fcorrelacao4.getValue()); //$JR_EXPR_ID=102$
                break;
            }
            case 103 : 
            {
                value = ((java.lang.String)parameter_Fcorrelacao5.getValue()); //$JR_EXPR_ID=103$
                break;
            }
            case 104 : 
            {
                value = ((java.lang.String)parameter_Fcorrelacao6.getValue()); //$JR_EXPR_ID=104$
                break;
            }
            case 105 : 
            {
                value = ((java.lang.String)parameter_Fcorrelacao7.getValue()); //$JR_EXPR_ID=105$
                break;
            }
            case 106 : 
            {
                value = ((java.lang.String)parameter_Fcorrelacao8.getValue()); //$JR_EXPR_ID=106$
                break;
            }
            case 107 : 
            {
                value = ((java.lang.String)parameter_Fjuros1.getValue()); //$JR_EXPR_ID=107$
                break;
            }
            case 108 : 
            {
                value = ((java.lang.String)parameter_Fjuros2.getValue()); //$JR_EXPR_ID=108$
                break;
            }
            case 109 : 
            {
                value = ((java.lang.String)parameter_Fjuros3.getValue()); //$JR_EXPR_ID=109$
                break;
            }
            case 110 : 
            {
                value = ((java.lang.String)parameter_Fjuros4.getValue()); //$JR_EXPR_ID=110$
                break;
            }
            case 111 : 
            {
                value = ((java.lang.String)parameter_Fjuros5.getValue()); //$JR_EXPR_ID=111$
                break;
            }
            case 112 : 
            {
                value = ((java.lang.String)parameter_Fjuros6.getValue()); //$JR_EXPR_ID=112$
                break;
            }
            case 113 : 
            {
                value = ((java.lang.String)parameter_Fjuros7.getValue()); //$JR_EXPR_ID=113$
                break;
            }
            case 114 : 
            {
                value = ((java.lang.String)parameter_Fjuros8.getValue()); //$JR_EXPR_ID=114$
                break;
            }
            case 115 : 
            {
                value = ((java.lang.String)parameter_Gcertidao.getValue()); //$JR_EXPR_ID=115$
                break;
            }
            case 116 : 
            {
                value = ((java.lang.String)parameter_Valorfiscal1.getValue()); //$JR_EXPR_ID=116$
                break;
            }
            case 117 : 
            {
                value = ((java.lang.String)parameter_Valorfiscal2.getValue()); //$JR_EXPR_ID=117$
                break;
            }
            case 118 : 
            {
                value = DATEFORMAT(new java.util.Date(),"dd/mm/yyyy"); //$JR_EXPR_ID=118$
                break;
            }
            case 119 : 
            {
                value = ((java.lang.String)parameter_Bnumero6.getValue()); //$JR_EXPR_ID=119$
                break;
            }
            case 120 : 
            {
                value = ((java.lang.String)parameter_Bnumero7.getValue()); //$JR_EXPR_ID=120$
                break;
            }
            case 121 : 
            {
                value = ((java.lang.String)parameter_Bnumero8.getValue()); //$JR_EXPR_ID=121$
                break;
            }
            case 122 : 
            {
                value = ((java.lang.String)parameter_Bdata8.getValue()); //$JR_EXPR_ID=122$
                break;
            }
            case 123 : 
            {
                value = ((java.lang.String)parameter_Bordem8.getValue()); //$JR_EXPR_ID=123$
                break;
            }
            case 124 : 
            {
                value = ((java.lang.String)parameter_Bnumero4.getValue()); //$JR_EXPR_ID=124$
                break;
            }
            case 125 : 
            {
                value = ((java.lang.String)parameter_Bnumero7.getValue()); //$JR_EXPR_ID=125$
                break;
            }
            case 126 : 
            {
                value = ((java.lang.String)parameter_Bnumero8.getValue()); //$JR_EXPR_ID=126$
                break;
            }
            case 127 : 
            {
                value = ((java.lang.String)parameter_Bdata1.getValue()); //$JR_EXPR_ID=127$
                break;
            }
            case 128 : 
            {
                value = ((java.lang.String)parameter_Bdata2.getValue()); //$JR_EXPR_ID=128$
                break;
            }
            case 129 : 
            {
                value = ((java.lang.String)parameter_Bordem1.getValue()); //$JR_EXPR_ID=129$
                break;
            }
            case 130 : 
            {
                value = ((java.lang.String)parameter_Bordem2.getValue()); //$JR_EXPR_ID=130$
                break;
            }
            case 131 : 
            {
                value = ((java.lang.String)parameter_Bordem4.getValue()); //$JR_EXPR_ID=131$
                break;
            }
            case 132 : 
            {
                value = ((java.lang.String)parameter_Bnatureza1.getValue()); //$JR_EXPR_ID=132$
                break;
            }
            case 133 : 
            {
                value = ((java.lang.String)parameter_Bnatureza2.getValue()); //$JR_EXPR_ID=133$
                break;
            }
            case 134 : 
            {
                value = ((java.lang.String)parameter_Bnatureza8.getValue()); //$JR_EXPR_ID=134$
                break;
            }
            case 135 : 
            {
                value = ((java.lang.String)parameter_Cdatadefi8.getValue()); //$JR_EXPR_ID=135$
                break;
            }
            case 136 : 
            {
                value = ((java.lang.String)parameter_Dprincipal8.getValue()); //$JR_EXPR_ID=136$
                break;
            }
            case 137 : 
            {
                value = ((java.lang.String)parameter_Dmulta8.getValue()); //$JR_EXPR_ID=137$
                break;
            }
            case 138 : 
            {
                value = ((java.lang.String)parameter_Dcorremone8.getValue()); //$JR_EXPR_ID=138$
                break;
            }
            case 139 : 
            {
                value = ((java.lang.String)parameter_Djurosmota8.getValue()); //$JR_EXPR_ID=139$
                break;
            }
            case 140 : 
            {
                value = ((java.lang.String)parameter_Dtotal8.getValue()); //$JR_EXPR_ID=140$
                break;
            }
            case 141 : 
            {
                value = ((java.lang.String)parameter_Dtotalencargos8.getValue()); //$JR_EXPR_ID=141$
                break;
            }
            case 142 : 
            {
                value = "//pgsrv08/publico/relatorios/producao/AssinaturaMarcelo.png"; //$JR_EXPR_ID=142$
                break;
            }
            case 143 : 
            {
                value = "//pgsrv08/publico/relatorios/producao/AssinaturaDrGuilherme.png"; //$JR_EXPR_ID=143$
                break;
            }
            case 144 : 
            {
                value = "//pgsrv08/publico/relatorios/producao/CERTIDAO VERSO ATUALIZADA outubro 2017.jpg"; //$JR_EXPR_ID=144$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateOld(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=0$
                break;
            }
            case 1 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=1$
                break;
            }
            case 2 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=2$
                break;
            }
            case 3 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=3$
                break;
            }
            case 4 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=4$
                break;
            }
            case 5 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=5$
                break;
            }
            case 6 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=6$
                break;
            }
            case 7 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=7$
                break;
            }
            case 8 : 
            {
                value = ((java.lang.String)parameter_Anome.getValue()); //$JR_EXPR_ID=8$
                break;
            }
            case 9 : 
            {
                value = ((java.lang.String)parameter_Bnumero1.getValue()); //$JR_EXPR_ID=9$
                break;
            }
            case 10 : 
            {
                value = ((java.lang.String)parameter_Bnumero2.getValue()); //$JR_EXPR_ID=10$
                break;
            }
            case 11 : 
            {
                value = ((java.lang.String)parameter_Bnumero3.getValue()); //$JR_EXPR_ID=11$
                break;
            }
            case 12 : 
            {
                value = ((java.lang.String)parameter_Bnumero4.getValue()); //$JR_EXPR_ID=12$
                break;
            }
            case 13 : 
            {
                value = ((java.lang.String)parameter_Bnumero5.getValue()); //$JR_EXPR_ID=13$
                break;
            }
            case 14 : 
            {
                value = ((java.lang.String)parameter_Bdata1.getValue()); //$JR_EXPR_ID=14$
                break;
            }
            case 15 : 
            {
                value = ((java.lang.String)parameter_Bdata2.getValue()); //$JR_EXPR_ID=15$
                break;
            }
            case 16 : 
            {
                value = ((java.lang.String)parameter_Bdata3.getValue()); //$JR_EXPR_ID=16$
                break;
            }
            case 17 : 
            {
                value = ((java.lang.String)parameter_Bdata4.getValue()); //$JR_EXPR_ID=17$
                break;
            }
            case 18 : 
            {
                value = ((java.lang.String)parameter_Bdata5.getValue()); //$JR_EXPR_ID=18$
                break;
            }
            case 19 : 
            {
                value = ((java.lang.String)parameter_Bdata6.getValue()); //$JR_EXPR_ID=19$
                break;
            }
            case 20 : 
            {
                value = ((java.lang.String)parameter_Bdata7.getValue()); //$JR_EXPR_ID=20$
                break;
            }
            case 21 : 
            {
                value = ((java.lang.String)parameter_Bordem1.getValue()); //$JR_EXPR_ID=21$
                break;
            }
            case 22 : 
            {
                value = ((java.lang.String)parameter_Bordem2.getValue()); //$JR_EXPR_ID=22$
                break;
            }
            case 23 : 
            {
                value = ((java.lang.String)parameter_Bordem3.getValue()); //$JR_EXPR_ID=23$
                break;
            }
            case 24 : 
            {
                value = ((java.lang.String)parameter_Bordem5.getValue()); //$JR_EXPR_ID=24$
                break;
            }
            case 25 : 
            {
                value = ((java.lang.String)parameter_Bordem6.getValue()); //$JR_EXPR_ID=25$
                break;
            }
            case 26 : 
            {
                value = ((java.lang.String)parameter_Bordem7.getValue()); //$JR_EXPR_ID=26$
                break;
            }
            case 27 : 
            {
                value = ((java.lang.String)parameter_Bnatureza1.getValue()); //$JR_EXPR_ID=27$
                break;
            }
            case 28 : 
            {
                value = ((java.lang.String)parameter_Bnatureza2.getValue()); //$JR_EXPR_ID=28$
                break;
            }
            case 29 : 
            {
                value = ((java.lang.String)parameter_Bnatureza3.getValue()); //$JR_EXPR_ID=29$
                break;
            }
            case 30 : 
            {
                value = ((java.lang.String)parameter_Bnatureza4.getValue()); //$JR_EXPR_ID=30$
                break;
            }
            case 31 : 
            {
                value = ((java.lang.String)parameter_Bnatureza5.getValue()); //$JR_EXPR_ID=31$
                break;
            }
            case 32 : 
            {
                value = ((java.lang.String)parameter_Bnatureza6.getValue()); //$JR_EXPR_ID=32$
                break;
            }
            case 33 : 
            {
                value = ((java.lang.String)parameter_Bnatureza7.getValue()); //$JR_EXPR_ID=33$
                break;
            }
            case 34 : 
            {
                value = ((java.lang.String)parameter_Cdatadefi1.getValue()); //$JR_EXPR_ID=34$
                break;
            }
            case 35 : 
            {
                value = ((java.lang.String)parameter_Cdatadefi2.getValue()); //$JR_EXPR_ID=35$
                break;
            }
            case 36 : 
            {
                value = ((java.lang.String)parameter_Cdatadefi3.getValue()); //$JR_EXPR_ID=36$
                break;
            }
            case 37 : 
            {
                value = ((java.lang.String)parameter_Cdatadefi4.getValue()); //$JR_EXPR_ID=37$
                break;
            }
            case 38 : 
            {
                value = ((java.lang.String)parameter_Cdatadefi5.getValue()); //$JR_EXPR_ID=38$
                break;
            }
            case 39 : 
            {
                value = ((java.lang.String)parameter_Cdatadefi6.getValue()); //$JR_EXPR_ID=39$
                break;
            }
            case 40 : 
            {
                value = ((java.lang.String)parameter_Cdatadefi7.getValue()); //$JR_EXPR_ID=40$
                break;
            }
            case 41 : 
            {
                value = ((java.lang.String)parameter_Dprincipal1.getValue()); //$JR_EXPR_ID=41$
                break;
            }
            case 42 : 
            {
                value = ((java.lang.String)parameter_Dprincipal2.getValue()); //$JR_EXPR_ID=42$
                break;
            }
            case 43 : 
            {
                value = ((java.lang.String)parameter_Dprincipal3.getValue()); //$JR_EXPR_ID=43$
                break;
            }
            case 44 : 
            {
                value = ((java.lang.String)parameter_Dprincipal4.getValue()); //$JR_EXPR_ID=44$
                break;
            }
            case 45 : 
            {
                value = ((java.lang.String)parameter_Dprincipal5.getValue()); //$JR_EXPR_ID=45$
                break;
            }
            case 46 : 
            {
                value = ((java.lang.String)parameter_Dprincipal6.getValue()); //$JR_EXPR_ID=46$
                break;
            }
            case 47 : 
            {
                value = ((java.lang.String)parameter_Dprincipal7.getValue()); //$JR_EXPR_ID=47$
                break;
            }
            case 48 : 
            {
                value = ((java.lang.String)parameter_Dmulta1.getValue()); //$JR_EXPR_ID=48$
                break;
            }
            case 49 : 
            {
                value = ((java.lang.String)parameter_Dmulta2.getValue()); //$JR_EXPR_ID=49$
                break;
            }
            case 50 : 
            {
                value = ((java.lang.String)parameter_Dmulta3.getValue()); //$JR_EXPR_ID=50$
                break;
            }
            case 51 : 
            {
                value = ((java.lang.String)parameter_Dmulta4.getValue()); //$JR_EXPR_ID=51$
                break;
            }
            case 52 : 
            {
                value = ((java.lang.String)parameter_Dmulta5.getValue()); //$JR_EXPR_ID=52$
                break;
            }
            case 53 : 
            {
                value = ((java.lang.String)parameter_Dmulta6.getValue()); //$JR_EXPR_ID=53$
                break;
            }
            case 54 : 
            {
                value = ((java.lang.String)parameter_Dmulta7.getValue()); //$JR_EXPR_ID=54$
                break;
            }
            case 55 : 
            {
                value = ((java.lang.String)parameter_Dcorremone1.getValue()); //$JR_EXPR_ID=55$
                break;
            }
            case 56 : 
            {
                value = ((java.lang.String)parameter_Dcorremone2.getValue()); //$JR_EXPR_ID=56$
                break;
            }
            case 57 : 
            {
                value = ((java.lang.String)parameter_Dcorremone3.getValue()); //$JR_EXPR_ID=57$
                break;
            }
            case 58 : 
            {
                value = ((java.lang.String)parameter_Dcorremone4.getValue()); //$JR_EXPR_ID=58$
                break;
            }
            case 59 : 
            {
                value = ((java.lang.String)parameter_Dcorremone5.getValue()); //$JR_EXPR_ID=59$
                break;
            }
            case 60 : 
            {
                value = ((java.lang.String)parameter_Dcorremone6.getValue()); //$JR_EXPR_ID=60$
                break;
            }
            case 61 : 
            {
                value = ((java.lang.String)parameter_Dcorremone7.getValue()); //$JR_EXPR_ID=61$
                break;
            }
            case 62 : 
            {
                value = ((java.lang.String)parameter_Djurosmota1.getValue()); //$JR_EXPR_ID=62$
                break;
            }
            case 63 : 
            {
                value = ((java.lang.String)parameter_Djurosmota2.getValue()); //$JR_EXPR_ID=63$
                break;
            }
            case 64 : 
            {
                value = ((java.lang.String)parameter_Djurosmota3.getValue()); //$JR_EXPR_ID=64$
                break;
            }
            case 65 : 
            {
                value = ((java.lang.String)parameter_Djurosmota4.getValue()); //$JR_EXPR_ID=65$
                break;
            }
            case 66 : 
            {
                value = ((java.lang.String)parameter_Djurosmota5.getValue()); //$JR_EXPR_ID=66$
                break;
            }
            case 67 : 
            {
                value = ((java.lang.String)parameter_Djurosmota6.getValue()); //$JR_EXPR_ID=67$
                break;
            }
            case 68 : 
            {
                value = ((java.lang.String)parameter_Djurosmota7.getValue()); //$JR_EXPR_ID=68$
                break;
            }
            case 69 : 
            {
                value = ((java.lang.String)parameter_Dtotal1.getValue()); //$JR_EXPR_ID=69$
                break;
            }
            case 70 : 
            {
                value = ((java.lang.String)parameter_Dtotal2.getValue()); //$JR_EXPR_ID=70$
                break;
            }
            case 71 : 
            {
                value = ((java.lang.String)parameter_Dtotal3.getValue()); //$JR_EXPR_ID=71$
                break;
            }
            case 72 : 
            {
                value = ((java.lang.String)parameter_Dtotal4.getValue()); //$JR_EXPR_ID=72$
                break;
            }
            case 73 : 
            {
                value = ((java.lang.String)parameter_Dtotal5.getValue()); //$JR_EXPR_ID=73$
                break;
            }
            case 74 : 
            {
                value = ((java.lang.String)parameter_Dtotal6.getValue()); //$JR_EXPR_ID=74$
                break;
            }
            case 75 : 
            {
                value = ((java.lang.String)parameter_Dtotal7.getValue()); //$JR_EXPR_ID=75$
                break;
            }
            case 76 : 
            {
                value = ((java.lang.String)parameter_Dtotalencargos1.getValue()); //$JR_EXPR_ID=76$
                break;
            }
            case 77 : 
            {
                value = ((java.lang.String)parameter_Dtotalencargos2.getValue()); //$JR_EXPR_ID=77$
                break;
            }
            case 78 : 
            {
                value = ((java.lang.String)parameter_Dtotalencargos3.getValue()); //$JR_EXPR_ID=78$
                break;
            }
            case 79 : 
            {
                value = ((java.lang.String)parameter_Dtotalencargos4.getValue()); //$JR_EXPR_ID=79$
                break;
            }
            case 80 : 
            {
                value = ((java.lang.String)parameter_Dtotalencargos5.getValue()); //$JR_EXPR_ID=80$
                break;
            }
            case 81 : 
            {
                value = ((java.lang.String)parameter_Dtotalencargos6.getValue()); //$JR_EXPR_ID=81$
                break;
            }
            case 82 : 
            {
                value = ((java.lang.String)parameter_Dtotalencargos7.getValue()); //$JR_EXPR_ID=82$
                break;
            }
            case 83 : 
            {
                value = ((java.lang.String)parameter_Ehonorario1.getValue()); //$JR_EXPR_ID=83$
                break;
            }
            case 84 : 
            {
                value = ((java.lang.String)parameter_Ehonorario2.getValue()); //$JR_EXPR_ID=84$
                break;
            }
            case 85 : 
            {
                value = ((java.lang.String)parameter_Ehonorario3.getValue()); //$JR_EXPR_ID=85$
                break;
            }
            case 86 : 
            {
                value = ((java.lang.String)parameter_Ehonorario4.getValue()); //$JR_EXPR_ID=86$
                break;
            }
            case 87 : 
            {
                value = ((java.lang.String)parameter_Ehonorario5.getValue()); //$JR_EXPR_ID=87$
                break;
            }
            case 88 : 
            {
                value = ((java.lang.String)parameter_Ehonorario6.getValue()); //$JR_EXPR_ID=88$
                break;
            }
            case 89 : 
            {
                value = ((java.lang.String)parameter_Ehonorario7.getValue()); //$JR_EXPR_ID=89$
                break;
            }
            case 90 : 
            {
                value = ((java.lang.String)parameter_Ehonorario8.getValue()); //$JR_EXPR_ID=90$
                break;
            }
            case 91 : 
            {
                value = ((java.lang.String)parameter_Edespesa1.getValue()); //$JR_EXPR_ID=91$
                break;
            }
            case 92 : 
            {
                value = ((java.lang.String)parameter_Edespesa2.getValue()); //$JR_EXPR_ID=92$
                break;
            }
            case 93 : 
            {
                value = ((java.lang.String)parameter_Edespesa3.getValue()); //$JR_EXPR_ID=93$
                break;
            }
            case 94 : 
            {
                value = ((java.lang.String)parameter_Edespesa4.getValue()); //$JR_EXPR_ID=94$
                break;
            }
            case 95 : 
            {
                value = ((java.lang.String)parameter_Edespesa5.getValue()); //$JR_EXPR_ID=95$
                break;
            }
            case 96 : 
            {
                value = ((java.lang.String)parameter_Edespesa6.getValue()); //$JR_EXPR_ID=96$
                break;
            }
            case 97 : 
            {
                value = ((java.lang.String)parameter_Edespesa7.getValue()); //$JR_EXPR_ID=97$
                break;
            }
            case 98 : 
            {
                value = ((java.lang.String)parameter_Edespesa8.getValue()); //$JR_EXPR_ID=98$
                break;
            }
            case 99 : 
            {
                value = ((java.lang.String)parameter_Fcorrelacao1.getValue()); //$JR_EXPR_ID=99$
                break;
            }
           default :
           {
               value = evaluateOld1(id);
           }
        }
        
        return value;
    }


    /**
     *
     */
    private Object evaluateOld1(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 100 : 
            {
                value = ((java.lang.String)parameter_Fcorrelacao2.getValue()); //$JR_EXPR_ID=100$
                break;
            }
            case 101 : 
            {
                value = ((java.lang.String)parameter_Fcorrelacao3.getValue()); //$JR_EXPR_ID=101$
                break;
            }
            case 102 : 
            {
                value = ((java.lang.String)parameter_Fcorrelacao4.getValue()); //$JR_EXPR_ID=102$
                break;
            }
            case 103 : 
            {
                value = ((java.lang.String)parameter_Fcorrelacao5.getValue()); //$JR_EXPR_ID=103$
                break;
            }
            case 104 : 
            {
                value = ((java.lang.String)parameter_Fcorrelacao6.getValue()); //$JR_EXPR_ID=104$
                break;
            }
            case 105 : 
            {
                value = ((java.lang.String)parameter_Fcorrelacao7.getValue()); //$JR_EXPR_ID=105$
                break;
            }
            case 106 : 
            {
                value = ((java.lang.String)parameter_Fcorrelacao8.getValue()); //$JR_EXPR_ID=106$
                break;
            }
            case 107 : 
            {
                value = ((java.lang.String)parameter_Fjuros1.getValue()); //$JR_EXPR_ID=107$
                break;
            }
            case 108 : 
            {
                value = ((java.lang.String)parameter_Fjuros2.getValue()); //$JR_EXPR_ID=108$
                break;
            }
            case 109 : 
            {
                value = ((java.lang.String)parameter_Fjuros3.getValue()); //$JR_EXPR_ID=109$
                break;
            }
            case 110 : 
            {
                value = ((java.lang.String)parameter_Fjuros4.getValue()); //$JR_EXPR_ID=110$
                break;
            }
            case 111 : 
            {
                value = ((java.lang.String)parameter_Fjuros5.getValue()); //$JR_EXPR_ID=111$
                break;
            }
            case 112 : 
            {
                value = ((java.lang.String)parameter_Fjuros6.getValue()); //$JR_EXPR_ID=112$
                break;
            }
            case 113 : 
            {
                value = ((java.lang.String)parameter_Fjuros7.getValue()); //$JR_EXPR_ID=113$
                break;
            }
            case 114 : 
            {
                value = ((java.lang.String)parameter_Fjuros8.getValue()); //$JR_EXPR_ID=114$
                break;
            }
            case 115 : 
            {
                value = ((java.lang.String)parameter_Gcertidao.getValue()); //$JR_EXPR_ID=115$
                break;
            }
            case 116 : 
            {
                value = ((java.lang.String)parameter_Valorfiscal1.getValue()); //$JR_EXPR_ID=116$
                break;
            }
            case 117 : 
            {
                value = ((java.lang.String)parameter_Valorfiscal2.getValue()); //$JR_EXPR_ID=117$
                break;
            }
            case 118 : 
            {
                value = DATEFORMAT(new java.util.Date(),"dd/mm/yyyy"); //$JR_EXPR_ID=118$
                break;
            }
            case 119 : 
            {
                value = ((java.lang.String)parameter_Bnumero6.getValue()); //$JR_EXPR_ID=119$
                break;
            }
            case 120 : 
            {
                value = ((java.lang.String)parameter_Bnumero7.getValue()); //$JR_EXPR_ID=120$
                break;
            }
            case 121 : 
            {
                value = ((java.lang.String)parameter_Bnumero8.getValue()); //$JR_EXPR_ID=121$
                break;
            }
            case 122 : 
            {
                value = ((java.lang.String)parameter_Bdata8.getValue()); //$JR_EXPR_ID=122$
                break;
            }
            case 123 : 
            {
                value = ((java.lang.String)parameter_Bordem8.getValue()); //$JR_EXPR_ID=123$
                break;
            }
            case 124 : 
            {
                value = ((java.lang.String)parameter_Bnumero4.getValue()); //$JR_EXPR_ID=124$
                break;
            }
            case 125 : 
            {
                value = ((java.lang.String)parameter_Bnumero7.getValue()); //$JR_EXPR_ID=125$
                break;
            }
            case 126 : 
            {
                value = ((java.lang.String)parameter_Bnumero8.getValue()); //$JR_EXPR_ID=126$
                break;
            }
            case 127 : 
            {
                value = ((java.lang.String)parameter_Bdata1.getValue()); //$JR_EXPR_ID=127$
                break;
            }
            case 128 : 
            {
                value = ((java.lang.String)parameter_Bdata2.getValue()); //$JR_EXPR_ID=128$
                break;
            }
            case 129 : 
            {
                value = ((java.lang.String)parameter_Bordem1.getValue()); //$JR_EXPR_ID=129$
                break;
            }
            case 130 : 
            {
                value = ((java.lang.String)parameter_Bordem2.getValue()); //$JR_EXPR_ID=130$
                break;
            }
            case 131 : 
            {
                value = ((java.lang.String)parameter_Bordem4.getValue()); //$JR_EXPR_ID=131$
                break;
            }
            case 132 : 
            {
                value = ((java.lang.String)parameter_Bnatureza1.getValue()); //$JR_EXPR_ID=132$
                break;
            }
            case 133 : 
            {
                value = ((java.lang.String)parameter_Bnatureza2.getValue()); //$JR_EXPR_ID=133$
                break;
            }
            case 134 : 
            {
                value = ((java.lang.String)parameter_Bnatureza8.getValue()); //$JR_EXPR_ID=134$
                break;
            }
            case 135 : 
            {
                value = ((java.lang.String)parameter_Cdatadefi8.getValue()); //$JR_EXPR_ID=135$
                break;
            }
            case 136 : 
            {
                value = ((java.lang.String)parameter_Dprincipal8.getValue()); //$JR_EXPR_ID=136$
                break;
            }
            case 137 : 
            {
                value = ((java.lang.String)parameter_Dmulta8.getValue()); //$JR_EXPR_ID=137$
                break;
            }
            case 138 : 
            {
                value = ((java.lang.String)parameter_Dcorremone8.getValue()); //$JR_EXPR_ID=138$
                break;
            }
            case 139 : 
            {
                value = ((java.lang.String)parameter_Djurosmota8.getValue()); //$JR_EXPR_ID=139$
                break;
            }
            case 140 : 
            {
                value = ((java.lang.String)parameter_Dtotal8.getValue()); //$JR_EXPR_ID=140$
                break;
            }
            case 141 : 
            {
                value = ((java.lang.String)parameter_Dtotalencargos8.getValue()); //$JR_EXPR_ID=141$
                break;
            }
            case 142 : 
            {
                value = "//pgsrv08/publico/relatorios/producao/AssinaturaMarcelo.png"; //$JR_EXPR_ID=142$
                break;
            }
            case 143 : 
            {
                value = "//pgsrv08/publico/relatorios/producao/AssinaturaDrGuilherme.png"; //$JR_EXPR_ID=143$
                break;
            }
            case 144 : 
            {
                value = "//pgsrv08/publico/relatorios/producao/CERTIDAO VERSO ATUALIZADA outubro 2017.jpg"; //$JR_EXPR_ID=144$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateEstimated(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=0$
                break;
            }
            case 1 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=1$
                break;
            }
            case 2 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=2$
                break;
            }
            case 3 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=3$
                break;
            }
            case 4 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=4$
                break;
            }
            case 5 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=5$
                break;
            }
            case 6 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=6$
                break;
            }
            case 7 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=7$
                break;
            }
            case 8 : 
            {
                value = ((java.lang.String)parameter_Anome.getValue()); //$JR_EXPR_ID=8$
                break;
            }
            case 9 : 
            {
                value = ((java.lang.String)parameter_Bnumero1.getValue()); //$JR_EXPR_ID=9$
                break;
            }
            case 10 : 
            {
                value = ((java.lang.String)parameter_Bnumero2.getValue()); //$JR_EXPR_ID=10$
                break;
            }
            case 11 : 
            {
                value = ((java.lang.String)parameter_Bnumero3.getValue()); //$JR_EXPR_ID=11$
                break;
            }
            case 12 : 
            {
                value = ((java.lang.String)parameter_Bnumero4.getValue()); //$JR_EXPR_ID=12$
                break;
            }
            case 13 : 
            {
                value = ((java.lang.String)parameter_Bnumero5.getValue()); //$JR_EXPR_ID=13$
                break;
            }
            case 14 : 
            {
                value = ((java.lang.String)parameter_Bdata1.getValue()); //$JR_EXPR_ID=14$
                break;
            }
            case 15 : 
            {
                value = ((java.lang.String)parameter_Bdata2.getValue()); //$JR_EXPR_ID=15$
                break;
            }
            case 16 : 
            {
                value = ((java.lang.String)parameter_Bdata3.getValue()); //$JR_EXPR_ID=16$
                break;
            }
            case 17 : 
            {
                value = ((java.lang.String)parameter_Bdata4.getValue()); //$JR_EXPR_ID=17$
                break;
            }
            case 18 : 
            {
                value = ((java.lang.String)parameter_Bdata5.getValue()); //$JR_EXPR_ID=18$
                break;
            }
            case 19 : 
            {
                value = ((java.lang.String)parameter_Bdata6.getValue()); //$JR_EXPR_ID=19$
                break;
            }
            case 20 : 
            {
                value = ((java.lang.String)parameter_Bdata7.getValue()); //$JR_EXPR_ID=20$
                break;
            }
            case 21 : 
            {
                value = ((java.lang.String)parameter_Bordem1.getValue()); //$JR_EXPR_ID=21$
                break;
            }
            case 22 : 
            {
                value = ((java.lang.String)parameter_Bordem2.getValue()); //$JR_EXPR_ID=22$
                break;
            }
            case 23 : 
            {
                value = ((java.lang.String)parameter_Bordem3.getValue()); //$JR_EXPR_ID=23$
                break;
            }
            case 24 : 
            {
                value = ((java.lang.String)parameter_Bordem5.getValue()); //$JR_EXPR_ID=24$
                break;
            }
            case 25 : 
            {
                value = ((java.lang.String)parameter_Bordem6.getValue()); //$JR_EXPR_ID=25$
                break;
            }
            case 26 : 
            {
                value = ((java.lang.String)parameter_Bordem7.getValue()); //$JR_EXPR_ID=26$
                break;
            }
            case 27 : 
            {
                value = ((java.lang.String)parameter_Bnatureza1.getValue()); //$JR_EXPR_ID=27$
                break;
            }
            case 28 : 
            {
                value = ((java.lang.String)parameter_Bnatureza2.getValue()); //$JR_EXPR_ID=28$
                break;
            }
            case 29 : 
            {
                value = ((java.lang.String)parameter_Bnatureza3.getValue()); //$JR_EXPR_ID=29$
                break;
            }
            case 30 : 
            {
                value = ((java.lang.String)parameter_Bnatureza4.getValue()); //$JR_EXPR_ID=30$
                break;
            }
            case 31 : 
            {
                value = ((java.lang.String)parameter_Bnatureza5.getValue()); //$JR_EXPR_ID=31$
                break;
            }
            case 32 : 
            {
                value = ((java.lang.String)parameter_Bnatureza6.getValue()); //$JR_EXPR_ID=32$
                break;
            }
            case 33 : 
            {
                value = ((java.lang.String)parameter_Bnatureza7.getValue()); //$JR_EXPR_ID=33$
                break;
            }
            case 34 : 
            {
                value = ((java.lang.String)parameter_Cdatadefi1.getValue()); //$JR_EXPR_ID=34$
                break;
            }
            case 35 : 
            {
                value = ((java.lang.String)parameter_Cdatadefi2.getValue()); //$JR_EXPR_ID=35$
                break;
            }
            case 36 : 
            {
                value = ((java.lang.String)parameter_Cdatadefi3.getValue()); //$JR_EXPR_ID=36$
                break;
            }
            case 37 : 
            {
                value = ((java.lang.String)parameter_Cdatadefi4.getValue()); //$JR_EXPR_ID=37$
                break;
            }
            case 38 : 
            {
                value = ((java.lang.String)parameter_Cdatadefi5.getValue()); //$JR_EXPR_ID=38$
                break;
            }
            case 39 : 
            {
                value = ((java.lang.String)parameter_Cdatadefi6.getValue()); //$JR_EXPR_ID=39$
                break;
            }
            case 40 : 
            {
                value = ((java.lang.String)parameter_Cdatadefi7.getValue()); //$JR_EXPR_ID=40$
                break;
            }
            case 41 : 
            {
                value = ((java.lang.String)parameter_Dprincipal1.getValue()); //$JR_EXPR_ID=41$
                break;
            }
            case 42 : 
            {
                value = ((java.lang.String)parameter_Dprincipal2.getValue()); //$JR_EXPR_ID=42$
                break;
            }
            case 43 : 
            {
                value = ((java.lang.String)parameter_Dprincipal3.getValue()); //$JR_EXPR_ID=43$
                break;
            }
            case 44 : 
            {
                value = ((java.lang.String)parameter_Dprincipal4.getValue()); //$JR_EXPR_ID=44$
                break;
            }
            case 45 : 
            {
                value = ((java.lang.String)parameter_Dprincipal5.getValue()); //$JR_EXPR_ID=45$
                break;
            }
            case 46 : 
            {
                value = ((java.lang.String)parameter_Dprincipal6.getValue()); //$JR_EXPR_ID=46$
                break;
            }
            case 47 : 
            {
                value = ((java.lang.String)parameter_Dprincipal7.getValue()); //$JR_EXPR_ID=47$
                break;
            }
            case 48 : 
            {
                value = ((java.lang.String)parameter_Dmulta1.getValue()); //$JR_EXPR_ID=48$
                break;
            }
            case 49 : 
            {
                value = ((java.lang.String)parameter_Dmulta2.getValue()); //$JR_EXPR_ID=49$
                break;
            }
            case 50 : 
            {
                value = ((java.lang.String)parameter_Dmulta3.getValue()); //$JR_EXPR_ID=50$
                break;
            }
            case 51 : 
            {
                value = ((java.lang.String)parameter_Dmulta4.getValue()); //$JR_EXPR_ID=51$
                break;
            }
            case 52 : 
            {
                value = ((java.lang.String)parameter_Dmulta5.getValue()); //$JR_EXPR_ID=52$
                break;
            }
            case 53 : 
            {
                value = ((java.lang.String)parameter_Dmulta6.getValue()); //$JR_EXPR_ID=53$
                break;
            }
            case 54 : 
            {
                value = ((java.lang.String)parameter_Dmulta7.getValue()); //$JR_EXPR_ID=54$
                break;
            }
            case 55 : 
            {
                value = ((java.lang.String)parameter_Dcorremone1.getValue()); //$JR_EXPR_ID=55$
                break;
            }
            case 56 : 
            {
                value = ((java.lang.String)parameter_Dcorremone2.getValue()); //$JR_EXPR_ID=56$
                break;
            }
            case 57 : 
            {
                value = ((java.lang.String)parameter_Dcorremone3.getValue()); //$JR_EXPR_ID=57$
                break;
            }
            case 58 : 
            {
                value = ((java.lang.String)parameter_Dcorremone4.getValue()); //$JR_EXPR_ID=58$
                break;
            }
            case 59 : 
            {
                value = ((java.lang.String)parameter_Dcorremone5.getValue()); //$JR_EXPR_ID=59$
                break;
            }
            case 60 : 
            {
                value = ((java.lang.String)parameter_Dcorremone6.getValue()); //$JR_EXPR_ID=60$
                break;
            }
            case 61 : 
            {
                value = ((java.lang.String)parameter_Dcorremone7.getValue()); //$JR_EXPR_ID=61$
                break;
            }
            case 62 : 
            {
                value = ((java.lang.String)parameter_Djurosmota1.getValue()); //$JR_EXPR_ID=62$
                break;
            }
            case 63 : 
            {
                value = ((java.lang.String)parameter_Djurosmota2.getValue()); //$JR_EXPR_ID=63$
                break;
            }
            case 64 : 
            {
                value = ((java.lang.String)parameter_Djurosmota3.getValue()); //$JR_EXPR_ID=64$
                break;
            }
            case 65 : 
            {
                value = ((java.lang.String)parameter_Djurosmota4.getValue()); //$JR_EXPR_ID=65$
                break;
            }
            case 66 : 
            {
                value = ((java.lang.String)parameter_Djurosmota5.getValue()); //$JR_EXPR_ID=66$
                break;
            }
            case 67 : 
            {
                value = ((java.lang.String)parameter_Djurosmota6.getValue()); //$JR_EXPR_ID=67$
                break;
            }
            case 68 : 
            {
                value = ((java.lang.String)parameter_Djurosmota7.getValue()); //$JR_EXPR_ID=68$
                break;
            }
            case 69 : 
            {
                value = ((java.lang.String)parameter_Dtotal1.getValue()); //$JR_EXPR_ID=69$
                break;
            }
            case 70 : 
            {
                value = ((java.lang.String)parameter_Dtotal2.getValue()); //$JR_EXPR_ID=70$
                break;
            }
            case 71 : 
            {
                value = ((java.lang.String)parameter_Dtotal3.getValue()); //$JR_EXPR_ID=71$
                break;
            }
            case 72 : 
            {
                value = ((java.lang.String)parameter_Dtotal4.getValue()); //$JR_EXPR_ID=72$
                break;
            }
            case 73 : 
            {
                value = ((java.lang.String)parameter_Dtotal5.getValue()); //$JR_EXPR_ID=73$
                break;
            }
            case 74 : 
            {
                value = ((java.lang.String)parameter_Dtotal6.getValue()); //$JR_EXPR_ID=74$
                break;
            }
            case 75 : 
            {
                value = ((java.lang.String)parameter_Dtotal7.getValue()); //$JR_EXPR_ID=75$
                break;
            }
            case 76 : 
            {
                value = ((java.lang.String)parameter_Dtotalencargos1.getValue()); //$JR_EXPR_ID=76$
                break;
            }
            case 77 : 
            {
                value = ((java.lang.String)parameter_Dtotalencargos2.getValue()); //$JR_EXPR_ID=77$
                break;
            }
            case 78 : 
            {
                value = ((java.lang.String)parameter_Dtotalencargos3.getValue()); //$JR_EXPR_ID=78$
                break;
            }
            case 79 : 
            {
                value = ((java.lang.String)parameter_Dtotalencargos4.getValue()); //$JR_EXPR_ID=79$
                break;
            }
            case 80 : 
            {
                value = ((java.lang.String)parameter_Dtotalencargos5.getValue()); //$JR_EXPR_ID=80$
                break;
            }
            case 81 : 
            {
                value = ((java.lang.String)parameter_Dtotalencargos6.getValue()); //$JR_EXPR_ID=81$
                break;
            }
            case 82 : 
            {
                value = ((java.lang.String)parameter_Dtotalencargos7.getValue()); //$JR_EXPR_ID=82$
                break;
            }
            case 83 : 
            {
                value = ((java.lang.String)parameter_Ehonorario1.getValue()); //$JR_EXPR_ID=83$
                break;
            }
            case 84 : 
            {
                value = ((java.lang.String)parameter_Ehonorario2.getValue()); //$JR_EXPR_ID=84$
                break;
            }
            case 85 : 
            {
                value = ((java.lang.String)parameter_Ehonorario3.getValue()); //$JR_EXPR_ID=85$
                break;
            }
            case 86 : 
            {
                value = ((java.lang.String)parameter_Ehonorario4.getValue()); //$JR_EXPR_ID=86$
                break;
            }
            case 87 : 
            {
                value = ((java.lang.String)parameter_Ehonorario5.getValue()); //$JR_EXPR_ID=87$
                break;
            }
            case 88 : 
            {
                value = ((java.lang.String)parameter_Ehonorario6.getValue()); //$JR_EXPR_ID=88$
                break;
            }
            case 89 : 
            {
                value = ((java.lang.String)parameter_Ehonorario7.getValue()); //$JR_EXPR_ID=89$
                break;
            }
            case 90 : 
            {
                value = ((java.lang.String)parameter_Ehonorario8.getValue()); //$JR_EXPR_ID=90$
                break;
            }
            case 91 : 
            {
                value = ((java.lang.String)parameter_Edespesa1.getValue()); //$JR_EXPR_ID=91$
                break;
            }
            case 92 : 
            {
                value = ((java.lang.String)parameter_Edespesa2.getValue()); //$JR_EXPR_ID=92$
                break;
            }
            case 93 : 
            {
                value = ((java.lang.String)parameter_Edespesa3.getValue()); //$JR_EXPR_ID=93$
                break;
            }
            case 94 : 
            {
                value = ((java.lang.String)parameter_Edespesa4.getValue()); //$JR_EXPR_ID=94$
                break;
            }
            case 95 : 
            {
                value = ((java.lang.String)parameter_Edespesa5.getValue()); //$JR_EXPR_ID=95$
                break;
            }
            case 96 : 
            {
                value = ((java.lang.String)parameter_Edespesa6.getValue()); //$JR_EXPR_ID=96$
                break;
            }
            case 97 : 
            {
                value = ((java.lang.String)parameter_Edespesa7.getValue()); //$JR_EXPR_ID=97$
                break;
            }
            case 98 : 
            {
                value = ((java.lang.String)parameter_Edespesa8.getValue()); //$JR_EXPR_ID=98$
                break;
            }
            case 99 : 
            {
                value = ((java.lang.String)parameter_Fcorrelacao1.getValue()); //$JR_EXPR_ID=99$
                break;
            }
           default :
           {
               value = evaluateEstimated1(id);
           }
        }
        
        return value;
    }


    /**
     *
     */
    private Object evaluateEstimated1(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 100 : 
            {
                value = ((java.lang.String)parameter_Fcorrelacao2.getValue()); //$JR_EXPR_ID=100$
                break;
            }
            case 101 : 
            {
                value = ((java.lang.String)parameter_Fcorrelacao3.getValue()); //$JR_EXPR_ID=101$
                break;
            }
            case 102 : 
            {
                value = ((java.lang.String)parameter_Fcorrelacao4.getValue()); //$JR_EXPR_ID=102$
                break;
            }
            case 103 : 
            {
                value = ((java.lang.String)parameter_Fcorrelacao5.getValue()); //$JR_EXPR_ID=103$
                break;
            }
            case 104 : 
            {
                value = ((java.lang.String)parameter_Fcorrelacao6.getValue()); //$JR_EXPR_ID=104$
                break;
            }
            case 105 : 
            {
                value = ((java.lang.String)parameter_Fcorrelacao7.getValue()); //$JR_EXPR_ID=105$
                break;
            }
            case 106 : 
            {
                value = ((java.lang.String)parameter_Fcorrelacao8.getValue()); //$JR_EXPR_ID=106$
                break;
            }
            case 107 : 
            {
                value = ((java.lang.String)parameter_Fjuros1.getValue()); //$JR_EXPR_ID=107$
                break;
            }
            case 108 : 
            {
                value = ((java.lang.String)parameter_Fjuros2.getValue()); //$JR_EXPR_ID=108$
                break;
            }
            case 109 : 
            {
                value = ((java.lang.String)parameter_Fjuros3.getValue()); //$JR_EXPR_ID=109$
                break;
            }
            case 110 : 
            {
                value = ((java.lang.String)parameter_Fjuros4.getValue()); //$JR_EXPR_ID=110$
                break;
            }
            case 111 : 
            {
                value = ((java.lang.String)parameter_Fjuros5.getValue()); //$JR_EXPR_ID=111$
                break;
            }
            case 112 : 
            {
                value = ((java.lang.String)parameter_Fjuros6.getValue()); //$JR_EXPR_ID=112$
                break;
            }
            case 113 : 
            {
                value = ((java.lang.String)parameter_Fjuros7.getValue()); //$JR_EXPR_ID=113$
                break;
            }
            case 114 : 
            {
                value = ((java.lang.String)parameter_Fjuros8.getValue()); //$JR_EXPR_ID=114$
                break;
            }
            case 115 : 
            {
                value = ((java.lang.String)parameter_Gcertidao.getValue()); //$JR_EXPR_ID=115$
                break;
            }
            case 116 : 
            {
                value = ((java.lang.String)parameter_Valorfiscal1.getValue()); //$JR_EXPR_ID=116$
                break;
            }
            case 117 : 
            {
                value = ((java.lang.String)parameter_Valorfiscal2.getValue()); //$JR_EXPR_ID=117$
                break;
            }
            case 118 : 
            {
                value = DATEFORMAT(new java.util.Date(),"dd/mm/yyyy"); //$JR_EXPR_ID=118$
                break;
            }
            case 119 : 
            {
                value = ((java.lang.String)parameter_Bnumero6.getValue()); //$JR_EXPR_ID=119$
                break;
            }
            case 120 : 
            {
                value = ((java.lang.String)parameter_Bnumero7.getValue()); //$JR_EXPR_ID=120$
                break;
            }
            case 121 : 
            {
                value = ((java.lang.String)parameter_Bnumero8.getValue()); //$JR_EXPR_ID=121$
                break;
            }
            case 122 : 
            {
                value = ((java.lang.String)parameter_Bdata8.getValue()); //$JR_EXPR_ID=122$
                break;
            }
            case 123 : 
            {
                value = ((java.lang.String)parameter_Bordem8.getValue()); //$JR_EXPR_ID=123$
                break;
            }
            case 124 : 
            {
                value = ((java.lang.String)parameter_Bnumero4.getValue()); //$JR_EXPR_ID=124$
                break;
            }
            case 125 : 
            {
                value = ((java.lang.String)parameter_Bnumero7.getValue()); //$JR_EXPR_ID=125$
                break;
            }
            case 126 : 
            {
                value = ((java.lang.String)parameter_Bnumero8.getValue()); //$JR_EXPR_ID=126$
                break;
            }
            case 127 : 
            {
                value = ((java.lang.String)parameter_Bdata1.getValue()); //$JR_EXPR_ID=127$
                break;
            }
            case 128 : 
            {
                value = ((java.lang.String)parameter_Bdata2.getValue()); //$JR_EXPR_ID=128$
                break;
            }
            case 129 : 
            {
                value = ((java.lang.String)parameter_Bordem1.getValue()); //$JR_EXPR_ID=129$
                break;
            }
            case 130 : 
            {
                value = ((java.lang.String)parameter_Bordem2.getValue()); //$JR_EXPR_ID=130$
                break;
            }
            case 131 : 
            {
                value = ((java.lang.String)parameter_Bordem4.getValue()); //$JR_EXPR_ID=131$
                break;
            }
            case 132 : 
            {
                value = ((java.lang.String)parameter_Bnatureza1.getValue()); //$JR_EXPR_ID=132$
                break;
            }
            case 133 : 
            {
                value = ((java.lang.String)parameter_Bnatureza2.getValue()); //$JR_EXPR_ID=133$
                break;
            }
            case 134 : 
            {
                value = ((java.lang.String)parameter_Bnatureza8.getValue()); //$JR_EXPR_ID=134$
                break;
            }
            case 135 : 
            {
                value = ((java.lang.String)parameter_Cdatadefi8.getValue()); //$JR_EXPR_ID=135$
                break;
            }
            case 136 : 
            {
                value = ((java.lang.String)parameter_Dprincipal8.getValue()); //$JR_EXPR_ID=136$
                break;
            }
            case 137 : 
            {
                value = ((java.lang.String)parameter_Dmulta8.getValue()); //$JR_EXPR_ID=137$
                break;
            }
            case 138 : 
            {
                value = ((java.lang.String)parameter_Dcorremone8.getValue()); //$JR_EXPR_ID=138$
                break;
            }
            case 139 : 
            {
                value = ((java.lang.String)parameter_Djurosmota8.getValue()); //$JR_EXPR_ID=139$
                break;
            }
            case 140 : 
            {
                value = ((java.lang.String)parameter_Dtotal8.getValue()); //$JR_EXPR_ID=140$
                break;
            }
            case 141 : 
            {
                value = ((java.lang.String)parameter_Dtotalencargos8.getValue()); //$JR_EXPR_ID=141$
                break;
            }
            case 142 : 
            {
                value = "//pgsrv08/publico/relatorios/producao/AssinaturaMarcelo.png"; //$JR_EXPR_ID=142$
                break;
            }
            case 143 : 
            {
                value = "//pgsrv08/publico/relatorios/producao/AssinaturaDrGuilherme.png"; //$JR_EXPR_ID=143$
                break;
            }
            case 144 : 
            {
                value = "//pgsrv08/publico/relatorios/producao/CERTIDAO VERSO ATUALIZADA outubro 2017.jpg"; //$JR_EXPR_ID=144$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


}
